// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.identityVerification.DanalIdentityVerificationBypass
import io.portone.sdk.android.type.entity.bypass.identityVerification.InicisUnifiedIdentityVerificationBypass
import io.portone.sdk.android.type.entity.bypass.identityVerification.KcpV2IdentityVerificationBypass
import kotlinx.parcelize.Parcelize

/**
 * **PG사 본인인증 창 호출 시 PG사로 그대로 bypass할 값들의 모음**
 */
@Parcelize
data class IdentityVerificationBypass(
    /**
     * **다날 bypass 파라미터**
     */
    val danal: DanalIdentityVerificationBypass? = null,
    /**
     * **KG이니시스 bypass 파라미터**
     */
    val inicisUnified: InicisUnifiedIdentityVerificationBypass? = null,
    /**
     * **KCP bypass 파라미터**
     */
    val kcpV2: KcpV2IdentityVerificationBypass? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        danal?.let { put("danal", danal.toJson()) }
        inicisUnified?.let { put("inicisUnified", inicisUnified.toJson()) }
        kcpV2?.let { put("kcpV2", kcpV2.toJson()) }
    }
}
