// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.InicisV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.KcpV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.NaverpayIssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.SmartroV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.TosspayV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.WelcomeIssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.payment.KakaopayPaymentBypass
import kotlinx.parcelize.Parcelize

@Parcelize
data class IssueBillingKeyBypass(
    /**
     * 카카오페이 bypass 파라미터
     */
    val kakaopay: KakaopayPaymentBypass?,
    /**
     * **스마트로 bypass 파라미터**
     */
    val smartroV2: SmartroV2IssueBillingKeyBypass?,
    /**
     * **네이버페이 bypass 파라미터**
     */
    val naverpay: NaverpayIssueBillingKeyBypass?,
    /**
     * **웰컴페이먼츠 bypass 파라미터**
     */
    val welcome: WelcomeIssueBillingKeyBypass?,
    /**
     * **토스페이 bypass 파라미터**
     */
    val tosspayV2: TosspayV2IssueBillingKeyBypass?,
    /**
     * **KG이니시스 bypass 파라미터**
     */
    val inicisV2: InicisV2IssueBillingKeyBypass?,
    /**
     * **KCP bypass 파라미터**
     */
    val kcpV2: KcpV2IssueBillingKeyBypass?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "kakaopay" to kakaopay?.let { kakaopay.toJson() },
        "smartro_v2" to smartroV2?.let { smartroV2.toJson() },
        "naverpay" to naverpay?.let { naverpay.toJson() },
        "welcome" to welcome?.let { welcome.toJson() },
        "tosspay_v2" to tosspayV2?.let { tosspayV2.toJson() },
        "inicis_v2" to inicisV2?.let { inicisV2.toJson() },
        "kcp_v2" to kcpV2?.let { kcpV2.toJson() }
    )
}
