// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.GalaxiaIssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.InicisV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.KcpV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.NaverpayIssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.SmartroV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.TosspayV2IssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.issueBillingKey.WelcomeIssueBillingKeyBypass
import io.portone.sdk.android.type.entity.bypass.payment.KakaopayPaymentBypass
import kotlinx.parcelize.Parcelize

@Parcelize
data class IssueBillingKeyBypass(
    /**
     * **KG이니시스 bypass 파라미터**
     */
    val inicisV2: InicisV2IssueBillingKeyBypass? = null,
    /**
     * **KCP bypass 파라미터**
     */
    val kcpV2: KcpV2IssueBillingKeyBypass? = null,
    /**
     * **스마트로 bypass 파라미터**
     */
    val smartroV2: SmartroV2IssueBillingKeyBypass? = null,
    /**
     * **웰컴페이먼츠 bypass 파라미터**
     */
    val welcome: WelcomeIssueBillingKeyBypass? = null,
    /**
     * **갤럭시아 bypass 파라미터**
     */
    val galaxia: GalaxiaIssueBillingKeyBypass? = null,
    /**
     * **네이버페이 bypass 파라미터**
     */
    val naverpay: NaverpayIssueBillingKeyBypass? = null,
    /**
     * 카카오페이 bypass 파라미터
     */
    val kakaopay: KakaopayPaymentBypass? = null,
    /**
     * **토스페이 bypass 파라미터**
     */
    val tosspayV2: TosspayV2IssueBillingKeyBypass? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        inicisV2?.let { put("inicis_v2", inicisV2.toJson()) }
        kcpV2?.let { put("kcp_v2", kcpV2.toJson()) }
        smartroV2?.let { put("smartro_v2", smartroV2.toJson()) }
        welcome?.let { put("welcome", welcome.toJson()) }
        galaxia?.let { put("galaxia", galaxia.toJson()) }
        naverpay?.let { put("naverpay", naverpay.toJson()) }
        kakaopay?.let { put("kakaopay", kakaopay.toJson()) }
        tosspayV2?.let { put("tosspay_v2", tosspayV2.toJson()) }
    }
}
