// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2LoadPaymentUIBypass
import kotlinx.parcelize.Parcelize

@Parcelize
data class LoadPaymentUIBypass(
    /**
     * **Paypal bypass 파라미터**
     */
    val paypalV2: PaypalV2LoadPaymentUIBypass? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        paypalV2?.let { put("paypal_v2", paypalV2.toJson()) }
    }
}
