// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2Bypass
import io.portone.sdk.android.type.entity.bypass.payment.GalaxiaPaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.HyphenBypass
import io.portone.sdk.android.type.entity.bypass.payment.InicisJpBypass
import io.portone.sdk.android.type.entity.bypass.payment.InicisV2Bypass
import io.portone.sdk.android.type.entity.bypass.payment.KakaopayPaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.KcpV2Bypass
import io.portone.sdk.android.type.entity.bypass.payment.KpnBypass
import io.portone.sdk.android.type.entity.bypass.payment.KsnetPaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.MobiliansV2Bypass
import io.portone.sdk.android.type.entity.bypass.payment.NaverpayPaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.NiceV2PaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.PayletterGlobalBypass
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.SmartroV2PaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayPaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.TosspayV2PaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.TosspaymentsPaymentBypass
import io.portone.sdk.android.type.entity.bypass.payment.WelcomePaymentBypass
import kotlinx.parcelize.Parcelize

/**
 * **PG사 결제창 호출 시 PG사로 그대로 bypass할 값들의 모음**
 */
@Parcelize
data class PaymentBypass(
    /**
     * 토스페이먼츠 bypass 파라미터
     */
    val tosspayments: TosspaymentsPaymentBypass? = null,
    /**
     * (신)나이스페이먼츠 bypass 파라미터
     */
    val niceV2: NiceV2PaymentBypass? = null,
    /**
     * **Paypal bypass 파라미터**
     */
    val paypalV2: PaypalV2PaymentBypass? = null,
    /**
     * KG이니시스 bypass 파라미터
     * 
     * KG이니시스는 PC 결제 모듈과 모바일 결제 모듈이 분리되어 있기 때문에 bypass 파라미터 또한 PC용과 모바일용이 분리되어 있습니다.
     */
    val inicisV2: InicisV2Bypass? = null,
    /**
     * NHN KCP bypass 파라미터
     */
    val kcpV2: KcpV2Bypass? = null,
    /**
     * 스마트로 V2 bypass 파라미터
     */
    val smartroV2: SmartroV2PaymentBypass? = null,
    /**
     * KSNET bypass 파라미터
     */
    val ksnet: KsnetPaymentBypass? = null,
    /**
     * 웰컴페이먼츠 bypass 파라미터
     */
    val welcome: WelcomePaymentBypass? = null,
    /**
     * KPN bypass 파라미터
     */
    val kpn: KpnBypass? = null,
    /**
     * 네이버페이 bypass 파라미터
     */
    val naverpay: NaverpayPaymentBypass? = null,
    /**
     * 카카오페이 bypass 파라미터
     */
    val kakaopay: KakaopayPaymentBypass? = null,
    /**
     * 토스페이 bypass 파라미터
     */
    val tosspayV2: TosspayV2PaymentBypass? = null,
    /**
     * 토스 브랜드페이 bypass 파라미터
     */
    val tossBrandpay: TossBrandpayPaymentBypass? = null,
    /**
     * 하이픈 bypass 파라미터
     */
    val hyphen: HyphenBypass? = null,
    /**
     * 엑심베이 V2 bypass 파라미터
     */
    val eximbayV2: EximbayV2Bypass? = null,
    /**
     * 갤럭시아 bypass 파라미터
     */
    val galaxia: GalaxiaPaymentBypass? = null,
    /**
     * 이니시스 일본 bypass 파라미터
     */
    val inicisJp: InicisJpBypass? = null,
    /**
     * 페이레터 해외결제 bypass 파라미터
     */
    val payletterGlobal: PayletterGlobalBypass? = null,
    /**
     * 모빌리언스 V2 bypass 파라미터
     */
    val mobiliansV2: MobiliansV2Bypass? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        tosspayments?.let { put("tosspayments", tosspayments.toJson()) }
        niceV2?.let { put("nice_v2", niceV2.toJson()) }
        paypalV2?.let { put("paypal_v2", paypalV2.toJson()) }
        inicisV2?.let { put("inicis_v2", inicisV2.toJson()) }
        kcpV2?.let { put("kcp_v2", kcpV2.toJson()) }
        smartroV2?.let { put("smartro_v2", smartroV2.toJson()) }
        ksnet?.let { put("ksnet", ksnet.toJson()) }
        welcome?.let { put("welcome", welcome.toJson()) }
        kpn?.let { put("kpn", kpn.toJson()) }
        naverpay?.let { put("naverpay", naverpay.toJson()) }
        kakaopay?.let { put("kakaopay", kakaopay.toJson()) }
        tosspayV2?.let { put("tosspay_v2", tosspayV2.toJson()) }
        tossBrandpay?.let { put("toss_brandpay", tossBrandpay.toJson()) }
        hyphen?.let { put("hyphen", hyphen.toJson()) }
        eximbayV2?.let { put("eximbay_v2", eximbayV2.toJson()) }
        galaxia?.let { put("galaxia", galaxia.toJson()) }
        inicisJp?.let { put("inicis_jp", inicisJp.toJson()) }
        payletterGlobal?.let { put("payletter_global", payletterGlobal.toJson()) }
        mobiliansV2?.let { put("mobilians_v2", mobiliansV2.toJson()) }
    }
}
