// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.identityVerification

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **KCP bypass 파라미터**
 */
@Parcelize
data class KcpV2IdentityVerificationBypass(
    /**
     * **DI 생성 시 사용할 사이트 ID**
     */
    val webSiteid: String?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "web_siteid" to webSiteid?.let { webSiteid }
    )
}
