// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.request

import android.os.Parcelable
import io.portone.sdk.type.entity.CardCompany
import kotlinx.parcelize.Parcelize

@Parcelize
data class IssueBillingKeyRequestUnionCard(
    /**
     * 카드 결제시 사용되는 카드사 코드
     */
    val cardCompany: CardCompany?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "cardCompany" to cardCompany?.let { cardCompany.toJson() }
    )
}
