// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.entity.Carrier
import kotlinx.parcelize.Parcelize

@Parcelize
data class IssueBillingKeyRequestUnionMobile(
    /**
     * 통신사 코드
     */
    val carrier: Carrier? = null,
    val avaliableCarriers: List<Carrier>? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        carrier?.let { put("carrier", carrier.toJson()) }
        avaliableCarriers?.let { put("avaliableCarriers", avaliableCarriers.map { it.toJson() }) }
    }
}
