// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.request

import android.os.Parcelable
import io.portone.sdk.type.entity.Carrier
import kotlinx.parcelize.Parcelize

@Parcelize
data class IssueBillingKeyAndPayRequestUnionMobile(
    /**
     * 통신사 코드
     */
    val carrier: Carrier?,
    val avaliableCarriers: List<Carrier>?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "carrier" to carrier?.let { carrier.toJson() },
        "avaliableCarriers" to avaliableCarriers?.let { avaliableCarriers.map { it.toJson() } }
    )
}
