// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.entity.BillingKeyMethod
import io.portone.sdk.android.type.entity.Currency
import io.portone.sdk.android.type.entity.Customer
import io.portone.sdk.android.type.entity.Iframe
import io.portone.sdk.android.type.entity.Locale
import io.portone.sdk.android.type.entity.OfferPeriod
import io.portone.sdk.android.type.entity.Popup
import io.portone.sdk.android.type.entity.ProductType
import io.portone.sdk.android.type.entity.WindowTypes
import io.portone.sdk.android.type.entity.bypass.IssueBillingKeyBypass
import io.portone.sdk.android.type.request.IssueBillingKeyRequestUnionCard
import io.portone.sdk.android.type.request.IssueBillingKeyRequestUnionEasyPay
import io.portone.sdk.android.type.request.IssueBillingKeyRequestUnionMobile
import io.portone.sdk.android.type.request.IssueBillingKeyRequestUnionPaypal
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class IssueBillingKeyRequest(
    /**
     * 빌링키 발급 창에 디스플레이 용으로 띄우는 금액
     */
    val displayAmount: Long? = null,
    /**
     * **화폐**
     * 
     * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 화폐 코드
     * 
     * 대한민국 원, 일본 엔이 아닌 화폐를 사용할 때에는 금액을 minor unit 단위로 입력해야 함에 유의하세요.
     */
    val currency: Currency? = null,
    /**
     * **상점 아이디**
     * 
     * 포트원 계정에 생성된 상점을 식별하는 고유한 값으로 [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel) 우측 상단에서 확인할 수 있습니다.
     */
    val storeId: String,
    /**
     * **채널 키**
     * 
     * 포트원에 등록된 결제 채널 중 하나를 지정합니다.
     * 
     * [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel)에서 채널 연동 후 채널 키를 확인할 수 있습니다.
     * 
     * 채널 키와 채널 그룹 ID 중 하나를 지정해야 합니다.
     */
    val channelKey: String? = null,
    /**
     * 빌링키 발급 수단
     */
    val billingKeyMethod: BillingKeyMethod,
    /**
     * 빌링키 발급 주문 명
     */
    val issueName: String? = null,
    /**
     * 빌링키 발급 주문 고유 번호
     */
    val issueId: String? = null,
    val customer: Customer? = null,
    /**
     * **환경 별 제공되는 결제/본인인증 창 유형**
     * 
     * - PG사에 따라 가능한 창 유형이 다릅니다.
     * - 전달되지 않았을 때 결정되는 기본 창이 다릅니다.
     * - 미입력 시, 해당 PG사의 기본 창 방식을 따릅니다.
     */
    val windowType: WindowTypes? = null,
    /**
     * **결과 리턴 방식을 리디렉션으로 강제**
     * 
     * `true`로 설정하면 원래 프로미스로 resolve 되었을 상황에서도
     * `redirectUrl`로 쿼리 파라미터와 함께 리디렉션합니다.
     * 
     * - `redirectUrl`이 없으면 기존처럼 프로미스로 반환합니다.
     * - 빌링키 발급 시작 전 발생하는 에러는 리디렉션하지 않습니다.
     */
    val forceRedirect: Boolean? = null,
    /**
     * **UI 언어**
     * 
     * KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A, 페이먼트월에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
     */
    val locale: Locale? = null,
    /**
     * **빌링키 발급 정보와 함께 관리하고 싶은 고객사 커스텀 JSON 데이터**
     */
    val customData: @RawValue Map<String, Any?>? = null,
    /**
     * **서비스 제공 기간**
     * 
     * range와 interval 중 하나를 입력해주세요.
     * 
     * - range: 제공 기간 범위
     * - interval: 제공 기간 주기
     * 
     * 예1) 2023년 1월 1일 00시 00분 00초(KST) ~
     * 
     * ```js
     * range: {
     * from: '2023-01-01T00:00:00+09:00'
     * }
     * ```
     * 
     * 예2) ~ 2023년 1월 1일 00시 00분 00초(KST)
     * 
     * ```js
     * range: {
     * to: '2023-01-01T00:00:00+09:00'
     * }
     * ```
     * 
     * 예3) 2023년 1월 1일 00시 00분 00초(KST) ~ 2023년 12월 31일 23시 59분 59초(KST)
     * 
     * ```js
     * range: {
     * from: '2023-12-31T23:59:59+09:00'
     * to: '2023-01-01T00:00:00+09:00'
     * }
     * ```
     * 
     * 예4) 30일 주기
     * `interval: '30d'`
     * 
     * 예5) 6개월 주기
     * `interval: '6m'`
     * 
     * 예6) 1년 주기
     * `interval: '1y'`
     */
    val offerPeriod: OfferPeriod? = null,
    /**
     * 앱 URL Scheme
     */
    val appScheme: String? = null,
    /**
     * 웹훅 URL
     */
    val noticeUrls: List<String>? = null,
    /**
     * **상품 유형**
     */
    val productType: ProductType? = null,
    val bypass: IssueBillingKeyBypass? = null,
    /**
     * **팝업 관련 필드**
     * 
     * UI가 팝업 창으로 열릴 때 적용되는 속성입니다.
     */
    val popup: Popup? = null,
    /**
     * **결제창이 iframe 방식일 경우 결제창에 적용할 속성**
     */
    val iframe: Iframe? = null,
    val card: IssueBillingKeyRequestUnionCard? = null,
    val mobile: IssueBillingKeyRequestUnionMobile? = null,
    val easyPay: IssueBillingKeyRequestUnionEasyPay? = null,
    val paypal: IssueBillingKeyRequestUnionPaypal? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        displayAmount?.let { put("displayAmount", displayAmount) }
        currency?.let { put("currency", currency.toJson()) }
        put("storeId", storeId)
        channelKey?.let { put("channelKey", channelKey) }
        put("billingKeyMethod", billingKeyMethod.toJson())
        issueName?.let { put("issueName", issueName) }
        issueId?.let { put("issueId", issueId) }
        customer?.let { put("customer", customer.toJson()) }
        windowType?.let { put("windowType", windowType.toJson()) }
        forceRedirect?.let { put("forceRedirect", forceRedirect) }
        locale?.let { put("locale", locale.toJson()) }
        customData?.let { put("customData", customData) }
        offerPeriod?.let { put("offerPeriod", offerPeriod.toJson()) }
        appScheme?.let { put("appScheme", appScheme) }
        noticeUrls?.let { put("noticeUrls", noticeUrls) }
        productType?.let { put("productType", productType.toJson()) }
        bypass?.let { put("bypass", bypass.toJson()) }
        popup?.let { put("popup", popup.toJson()) }
        iframe?.let { put("iframe", iframe.toJson()) }
        card?.let { put("card", card.toJson()) }
        mobile?.let { put("mobile", mobile.toJson()) }
        easyPay?.let { put("easyPay", easyPay.toJson()) }
        paypal?.let { put("paypal", paypal.toJson()) }
    }
}
