// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.entity.GiftCertificateType
import kotlinx.parcelize.Parcelize

/**
 * **상품권 결제 설정**
 */
@Parcelize
data class PaymentRequestUnionGiftCertificate(
    /**
     * **상품권 종류**
     */
    val giftCertificateType: GiftCertificateType? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        giftCertificateType?.let { put("giftCertificateType", giftCertificateType.toJson()) }
    }
}
