// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.entity.Address
import io.portone.sdk.android.type.entity.Country
import io.portone.sdk.android.type.entity.Currency
import io.portone.sdk.android.type.entity.Customer
import io.portone.sdk.android.type.entity.Iframe
import io.portone.sdk.android.type.entity.Locale
import io.portone.sdk.android.type.entity.OfferPeriod
import io.portone.sdk.android.type.entity.PaymentPayMethod
import io.portone.sdk.android.type.entity.Popup
import io.portone.sdk.android.type.entity.Product
import io.portone.sdk.android.type.entity.ProductType
import io.portone.sdk.android.type.entity.StoreDetails
import io.portone.sdk.android.type.entity.WindowTypes
import io.portone.sdk.android.type.entity.bypass.PaymentBypass
import io.portone.sdk.android.type.request.PaymentRequestUnionAlipay
import io.portone.sdk.android.type.request.PaymentRequestUnionAlipayPlus
import io.portone.sdk.android.type.request.PaymentRequestUnionCard
import io.portone.sdk.android.type.request.PaymentRequestUnionConvenienceStore
import io.portone.sdk.android.type.request.PaymentRequestUnionEasyPay
import io.portone.sdk.android.type.request.PaymentRequestUnionGiftCertificate
import io.portone.sdk.android.type.request.PaymentRequestUnionMobile
import io.portone.sdk.android.type.request.PaymentRequestUnionPaypal
import io.portone.sdk.android.type.request.PaymentRequestUnionTransfer
import io.portone.sdk.android.type.request.PaymentRequestUnionVirtualAccount
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class PaymentRequest(
    /**
     * **상점 아이디**
     * 
     * 포트원 계정에 생성된 상점을 식별하는 고유한 값으로 [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel) 우측 상단에서 확인할 수 있습니다.
     */
    val storeId: String,
    /**
     * **결제 ID**
     * 
     * 고객사에서 임의로 ID를 정합니다.
     * 
     * 이미 결제 완료된 `paymentId`로 결제를 요청하는 경우 실패합니다.
     */
    val paymentId: String,
    /**
     * **주문명**
     */
    val orderName: String,
    /**
     * **주문 상세 내용**
     */
    val orderDetail: String? = null,
    /**
     * **결제 금액**
     * 
     * 결제 금액을 정수로 나타냅니다.
     * 
     * 해외 통화의 경우 통화의 최소 단위(minor unit)를 기준으로 합니다. 예를 들어, USD의 최소 단위는 센트(0.01 USD)이므로, 6 USD의 경우 100배하여 600으로 입력합니다.
     * 
     * 최소 단위는 [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)에 표준화된 것을 기준으로 합니다.
     * 
     * - KRW: 1배
     * - USD: 100배
     * - JPY: 1배
     */
    val totalAmount: Long,
    /**
     * **화폐**
     * 
     * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) 화폐 코드
     * 
     * 대한민국 원, 일본 엔이 아닌 화폐를 사용할 때에는 금액을 minor unit 단위로 입력해야 함에 유의하세요.
     */
    val currency: Currency,
    /**
     * **결제수단 구분코드**
     * 
     * PG사별 지원되는 결제수단이 모두 상이합니다.
     * 
     * [각 PG사별 결제 연동 가이드](https://developers.portone.io/opi/ko/integration/pg/v2/readme?v=v2)를 참고하세요
     */
    val payMethod: PaymentPayMethod,
    /**
     * **채널 키**
     * 
     * 포트원에 등록된 결제 채널 중 하나를 지정합니다.
     * 
     * [관리자 콘솔 > 연동 정보](https://admin.portone.io/integration-v2/manage/channel)에서 채널 연동 후 채널 키를 확인할 수 있습니다.
     * 
     * 채널 키와 채널 그룹 ID 중 하나를 지정해야 합니다.
     */
    val channelKey: String? = null,
    /**
     * **채널 그룹 ID**
     * 
     * 채널 그룹 ID를 지정하여 결제창을 호출하면, 채널 그룹 내 설정된 비율에 따라 확률적으로 하나의 채널이 선택됩니다. [관리자 콘솔 > 연동 관리 > 스마트 라우팅](https://admin.portone.io/integration-v2/smart-routing)에서 설정합니다.
     * 
     * 채널 키와 채널 그룹 ID 중 하나를 지정해야 합니다.
     */
    val channelGroupId: String? = null,
    /**
     * **면세 금액**
     * 
     * 미입력 시 0으로 취급됩니다.
     */
    val taxFreeAmount: Long? = null,
    /**
     * **부가세 금액**
     * 
     * 미입력 시 과세 금액의 1/11로 자동 계산됩니다.
     */
    val vatAmount: Long? = null,
    val customer: Customer? = null,
    /**
     * **환경 별 제공되는 결제/본인인증 창 유형**
     * 
     * - PG사에 따라 가능한 창 유형이 다릅니다.
     * - 전달되지 않았을 때 결정되는 기본 창이 다릅니다.
     * - 미입력 시, 해당 PG사의 기본 창 방식을 따릅니다.
     */
    val windowType: WindowTypes? = null,
    /**
     * **결과 리턴 방식을 리디렉션으로 강제**
     * 
     * `true`로 설정하면 원래 프로미스로 resolve 되었을 상황에서도
     * `redirectUrl`로 쿼리 파라미터와 함께 리디렉션합니다.
     * 
     * - `redirectUrl`이 없으면 기존처럼 프로미스로 반환합니다.
     * - 결제 시작 전 발생하는 에러는 리디렉션하지 않습니다.
     */
    val forceRedirect: Boolean? = null,
    /**
     * **웹훅 수신 URL**
     * 
     * 포트원 관리자 콘솔에 설정한 웹훅 URL 대신 사용할 웹훅 URL을 결제시마다 설정할 수 있습니다.
     * 
     * 올바른 HTTP(S) URL이어야 합니다.
     */
    val noticeUrls: List<String>? = null,
    /**
     * **결제 승인 여부 확인 URL**
     * 
     * 컨펌 프로세스 웹훅을 수신할 URL입니다.
     * 
     * 올바른 HTTP(S) URL이어야 합니다.
     * 
     * 별도 요청이 필요합니다. (<tech.support@portone.io>)
     */
    val confirmUrl: String? = null,
    /**
     * **모바일 결제 후 고객사 앱으로 복귀를 위한 URL scheme**
     * 
     * - WebView 환경 결제시 필수설정 항목 입니다.
     * - ISP/앱카드 앱에서 결제정보인증 후 기존 앱으로 복귀할 때 사용합니다.
     */
    val appScheme: String? = null,
    /**
     * **에스크로 결제 여부**
     * 
     * 미입력 시 기본값: `false`
     * 
     * - 에스크로 설정은 PG사와 협의 이후 진행되어야 합니다.
     */
    val isEscrow: Boolean? = null,
    /**
     * **구매 상품 정보**
     */
    val products: List<Product>? = null,
    /**
     * **문화비 지출 여부**
     * 
     * 도서, 공연, 박물관 등 문화비 지출 여부
     */
    val isCulturalExpense: Boolean? = null,
    /**
     * **UI 언어**
     * 
     * KG이니시스, 스마트로, KSNET, 웰컴페이먼츠 (PC), 한국결제네트웍스, 엑심베이, Triple-A, 페이먼트월에서 설정 가능하며, PG마다 지원하는 언어 목록은 차이가 있습니다.
     */
    val locale: Locale? = null,
    /**
     * **결제 정보에 포함할 고객사 커스텀 JSON 데이터**
     */
    val customData: @RawValue Map<String, Any?>? = null,
    /**
     * **국가**
     * 
     * [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
     */
    val country: Country? = null,
    /**
     * **상품 유형**
     */
    val productType: ProductType? = null,
    /**
     * **서비스 제공 기간**
     * 
     * range와 interval 중 하나를 입력해주세요.
     * 
     * - range: 제공 기간 범위
     * - interval: 제공 기간 주기
     * 
     * 예1) 2023년 1월 1일 00시 00분 00초(KST) ~
     * 
     * ```js
     * range: {
     * from: '2023-01-01T00:00:00+09:00'
     * }
     * ```
     * 
     * 예2) ~ 2023년 1월 1일 00시 00분 00초(KST)
     * 
     * ```js
     * range: {
     * to: '2023-01-01T00:00:00+09:00'
     * }
     * ```
     * 
     * 예3) 2023년 1월 1일 00시 00분 00초(KST) ~ 2023년 12월 31일 23시 59분 59초(KST)
     * 
     * ```js
     * range: {
     * from: '2023-12-31T23:59:59+09:00'
     * to: '2023-01-01T00:00:00+09:00'
     * }
     * ```
     * 
     * 예4) 30일 주기
     * `interval: '30d'`
     * 
     * 예5) 6개월 주기
     * `interval: '6m'`
     * 
     * 예6) 1년 주기
     * `interval: '1y'`
     */
    val offerPeriod: OfferPeriod? = null,
    /**
     * **상점 정보**
     * 
     * - KSNET 카카오페이의 경우 필수 입력
     * - 나이스페이먼츠의 경우 매출 전표에 표기 할 용도로 선택 입력
     * - KG이니시스 일본결제의 경우 JPPG(gmoPayment) 결제의 상점정보로 사용되거나 편의점 결제 시 영수증 표시 정보로 사용됨.
     */
    val storeDetails: StoreDetails? = null,
    /**
     * **주소 정보**
     */
    val shippingAddress: Address? = null,
    /**
     * **프로모션 아이디**
     * 
     * 포트원의 프로모션 기능 이용시 지정합니다.
     */
    val promotionId: String? = null,
    /**
     * **Merpay 상품 카테고리 ID**
     */
    val merpayCategoryId: String? = null,
    /**
     * **팝업 관련 필드**
     * 
     * UI가 팝업 창으로 열릴 때 적용되는 속성입니다.
     */
    val popup: Popup? = null,
    /**
     * **결제창이 iframe 방식일 경우 결제창에 적용할 속성**
     */
    val iframe: Iframe? = null,
    /**
     * **PG사 결제창 호출 시 PG사로 그대로 bypass할 값들의 모음**
     */
    val bypass: PaymentBypass? = null,
    /**
     * **카드 결제 설정**
     */
    val card: PaymentRequestUnionCard? = null,
    /**
     * **가상계좌 결제 설정**
     */
    val virtualAccount: PaymentRequestUnionVirtualAccount? = null,
    /**
     * **계좌이체 결제 설정**
     */
    val transfer: PaymentRequestUnionTransfer? = null,
    /**
     * **휴대전화 결제 설정**
     */
    val mobile: PaymentRequestUnionMobile? = null,
    /**
     * **상품권 결제 설정**
     */
    val giftCertificate: PaymentRequestUnionGiftCertificate? = null,
    val easyPay: PaymentRequestUnionEasyPay? = null,
    val paypal: PaymentRequestUnionPaypal? = null,
    val alipay: PaymentRequestUnionAlipay? = null,
    val convenienceStore: PaymentRequestUnionConvenienceStore? = null,
    val alipayPlus: PaymentRequestUnionAlipayPlus? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("storeId", storeId)
        put("paymentId", paymentId)
        put("orderName", orderName)
        orderDetail?.let { put("orderDetail", orderDetail) }
        put("totalAmount", totalAmount)
        put("currency", currency.toJson())
        put("payMethod", payMethod.toJson())
        channelKey?.let { put("channelKey", channelKey) }
        channelGroupId?.let { put("channelGroupId", channelGroupId) }
        taxFreeAmount?.let { put("taxFreeAmount", taxFreeAmount) }
        vatAmount?.let { put("vatAmount", vatAmount) }
        customer?.let { put("customer", customer.toJson()) }
        windowType?.let { put("windowType", windowType.toJson()) }
        forceRedirect?.let { put("forceRedirect", forceRedirect) }
        noticeUrls?.let { put("noticeUrls", noticeUrls) }
        confirmUrl?.let { put("confirmUrl", confirmUrl) }
        appScheme?.let { put("appScheme", appScheme) }
        isEscrow?.let { put("isEscrow", isEscrow) }
        products?.let { put("products", products.map { it.toJson() }) }
        isCulturalExpense?.let { put("isCulturalExpense", isCulturalExpense) }
        locale?.let { put("locale", locale.toJson()) }
        customData?.let { put("customData", customData) }
        country?.let { put("country", country.toJson()) }
        productType?.let { put("productType", productType.toJson()) }
        offerPeriod?.let { put("offerPeriod", offerPeriod.toJson()) }
        storeDetails?.let { put("storeDetails", storeDetails.toJson()) }
        shippingAddress?.let { put("shippingAddress", shippingAddress.toJson()) }
        promotionId?.let { put("promotionId", promotionId) }
        merpayCategoryId?.let { put("merpayCategoryId", merpayCategoryId) }
        popup?.let { put("popup", popup.toJson()) }
        iframe?.let { put("iframe", iframe.toJson()) }
        bypass?.let { put("bypass", bypass.toJson()) }
        card?.let { put("card", card.toJson()) }
        virtualAccount?.let { put("virtualAccount", virtualAccount.toJson()) }
        transfer?.let { put("transfer", transfer.toJson()) }
        mobile?.let { put("mobile", mobile.toJson()) }
        giftCertificate?.let { put("giftCertificate", giftCertificate.toJson()) }
        easyPay?.let { put("easyPay", easyPay.toJson()) }
        paypal?.let { put("paypal", paypal.toJson()) }
        alipay?.let { put("alipay", alipay.toJson()) }
        convenienceStore?.let { put("convenienceStore", convenienceStore.toJson()) }
        alipayPlus?.let { put("alipayPlus", alipayPlus.toJson()) }
    }
}
