// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.request.PaymentRequestUnionConvenienceStorePaymentDeadline
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaymentRequestUnionConvenienceStore(
    /**
     * **편의점결제 지불기한**
     */
    val paymentDeadline: PaymentRequestUnionConvenienceStorePaymentDeadline?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        paymentDeadline?.let { put("paymentDeadline", paymentDeadline.toJson()) }
    }
}
