// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
class PaymentRequestUnionAlipay : Parcelable {
    fun toJson(): Map<String, Any> = emptyMap()
}
