// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.entity.EasyPayProvider
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaymentRequestUnionAlipayPlus(
    /**
     * PG 제휴로 간편결제를 이용할 때, 간편결제 UI를 직접 호출할 수 있는 간편결제
     */
    val easyPayProvider: EasyPayProvider? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        easyPayProvider?.let { put("easyPayProvider", easyPayProvider.toJson()) }
    }
}
