// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.request

import android.os.Parcelable
import io.portone.sdk.android.type.entity.Bank
import io.portone.sdk.android.type.entity.CashReceiptType
import io.portone.sdk.android.type.request.PaymentRequestUnionVirtualAccountAccountExpiry
import io.portone.sdk.android.type.request.PaymentRequestUnionVirtualAccountFixedOption
import kotlinx.parcelize.Parcelize

/**
 * **가상계좌 결제 설정**
 */
@Parcelize
data class PaymentRequestUnionVirtualAccount(
    /**
     * **현금영수증 발급 유형**
     */
    val cashReceiptType: CashReceiptType? = null,
    /**
     * **현금영수증 구매자 번호**
     * 
     * 카드일련번호, 주민등록번호, 사업자등록번호, 휴대전화번호 중 하나입니다. 스마트로에서 PG UI를 건너뛸 때 사용합니다.
     */
    val customerIdentifier: String? = null,
    /**
     * **고정식 가상계좌 설정**
     */
    val fixedOption: PaymentRequestUnionVirtualAccountFixedOption? = null,
    /**
     * 가상계좌 발급시 사용되는 은행 코드
     */
    val bankCode: Bank? = null,
    /**
     * **가상계좌 입금 만료 기한**
     * 
     * 토스페이먼츠, KG이니시스, NHN KCP에서 지원합니다.
     * 
     * `validHours`와 `dueDate` 중 하나만 지정합니다.
     */
    val accountExpiry: PaymentRequestUnionVirtualAccountAccountExpiry? = null,
    /**
     * **선택 가능 은행 목록**
     * 
     * 가상계좌 발급 UI에서 선택할 수 있는 은행 목록을 지정합니다. KCP에서만 지원합니다.
     */
    val availableBanks: List<Bank>? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        cashReceiptType?.let { put("cashReceiptType", cashReceiptType.toJson()) }
        customerIdentifier?.let { put("customerIdentifier", customerIdentifier) }
        fixedOption?.let { put("fixedOption", fixedOption.toJson()) }
        bankCode?.let { put("bankCode", bankCode.toJson()) }
        accountExpiry?.let { put("accountExpiry", accountExpiry.toJson()) }
        availableBanks?.let { put("availableBanks", availableBanks.map { it.toJson() }) }
    }
}
