// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

/**
 * 카드 결제시 사용되는 카드사 코드
 */
enum class CardCompany {
    /**
     * KDB산업은행 카드
     */
    KOREA_DEVELOPMENT_BANK,
    /**
     * 새마을금고 카드
     */
    KFCC,
    /**
     * 신협 카드
     */
    SHINHYUP,
    /**
     * 우체국 카드
     */
    EPOST,
    /**
     * 저축은행 카드
     */
    SAVINGS_BANK_KOREA,
    /**
     * 카카오뱅크 카드
     */
    KAKAO_BANK,
    /**
     * 우리카드
     */
    WOORI_CARD,
    /**
     * BC카드
     */
    BC_CARD,
    /**
     * 광주카드
     */
    GWANGJU_CARD,
    /**
     * 삼성카드
     */
    SAMSUNG_CARD,
    /**
     * 신한카드
     */
    SHINHAN_CARD,
    /**
     * 현대카드
     */
    HYUNDAI_CARD,
    /**
     * 롯데카드
     */
    LOTTE_CARD,
    /**
     * 수협카드
     */
    SUHYUP_CARD,
    /**
     * 씨티카드
     */
    CITI_CARD,
    /**
     * NH 농협카드
     */
    NH_CARD,
    /**
     * 전북카드
     */
    JEONBUK_CARD,
    /**
     * 제주카드
     */
    JEJU_CARD,
    /**
     * 하나카드
     */
    HANA_CARD,
    /**
     * 국민카드
     */
    KOOKMIN_CARD,
    /**
     * K뱅크 카드
     */
    K_BANK,
    /**
     * 토스뱅크 카드
     */
    TOSS_BANK,
    /**
     * 미래에셋증권 카드
     */
    MIRAE_ASSET_SECURITIES;

    fun toJson(): String = name
}
