// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

/**
 * PG 제휴로 간편결제를 이용할 때, 간편결제 UI를 직접 호출할 수 있는 간편결제
 */
enum class EasyPayProvider {
    /**
     * 네이버페이
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - 스마트로
     * - NHN KCP
     * - KSNET
     * - 한국결제네트웍스
     */
    NAVERPAY,
    /**
     * 카카오페이
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - 스마트로
     * - NHN KCP
     * - KSNET
     * - 한국결제네트웍스
     * - 웰컴페이먼츠
     */
    KAKAOPAY,
    /**
     * 토스페이
     * 
     * - 토스페이먼츠
     * - KG이니시스
     * - NHN KCP
     * - 스마트로
     * - 한국결제네트웍스
     * - 웰컴페이먼츠
     */
    TOSSPAY,
    /**
     * 페이코
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - 스마트로
     * - KSNET
     * - 한국결제네트웍스
     * - 웰컴페이먼츠
     */
    PAYCO,
    /**
     * 차이페이
     */
    CHAI,
    /**
     * L페이
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - 스마트로
     * - KSNET
     * - 웰컴페이먼츠
     */
    LPAY,
    /**
     * K페이
     */
    KPAY,
    /**
     * SSG페이
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - NHN KCP
     * - KSNET
     */
    SSGPAY,
    /**
     * 삼성페이
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - NHN KCP
     * - 스마트로
     * - 한국결제네트웍스
     */
    SAMSUNGPAY,
    /**
     * 애플페이
     * 
     * - 토스페이먼츠
     * - 나이스페이먼츠
     * - KG이니시스
     * - NHN KCP
     */
    APPLEPAY,
    /**
     * LG페이
     * 
     * - 토스페이먼츠
     */
    LGPAY,
    /**
     * SK페이
     * 
     * - 나이스페이먼츠
     */
    SKPAY,
    /**
     * 핀페이
     * 
     * - 스마트로
     */
    PINPAY,
    /**
     * 토스 브랜드페이
     */
    TOSS_BRANDPAY,
    /**
     * 하이픈
     */
    HYPHEN,
    /**
     * 라인페이
     * 
     * - 스마트로
     */
    LINEPAY,
    /**
     * 티머니
     * 
     * - 스마트로
     */
    TMONEY,
    /**
     * PayPay
     * 
     * - KG이니시스 JPPG/SBPS 일본결제
     */
    PAYPAY,
    /**
     * 아마존페이
     * 
     * - KG이니시스 JPPG 일본결제
     */
    AMAZONPAY,
    /**
     * 라쿠텐페이
     * 
     * - KG이니시스 JPPG 일본결제
     */
    RAKUTENPAY,
    /**
     * dBarai
     * 
     * - KG이니시스 JPPG 일본결제
     */
    DBARAI,
    /**
     * auPAY
     * 
     * - KG이니시스 JPPG 일본결제
     */
    AUPAY,
    /**
     * Merpay
     * 
     * - KG이니시스 JPPG 일본결제
     */
    MERPAY,
    /**
     * Alipay
     * 
     * - KICC V2 알리페이 플러스
     */
    ALIPAY,
    /**
     * Alipay (HK)
     * 
     * - KICC V2 알리페이 플러스
     */
    ALIPAY_HK,
    /**
     * TrueMoney
     * 
     * - KICC V2 알리페이 플러스
     */
    TRUE_MONEY,
    /**
     * Touch'n Go eWallet
     * 
     * - KICC V2 알리페이 플러스
     */
    TOUCH_N_GO,
    /**
     * GCash
     * 
     * - KICC V2 알리페이 플러스
     */
    GCASH,
    /**
     * DANA
     * 
     * - KICC V2 알리페이 플러스
     */
    DANA,
    /**
     * Rabbit LINE Pay
     * 
     * - KICC V2 알리페이 플러스
     */
    RABBIT_LINE_PAY,
    /**
     * BPI (Bank of the Philippine Islands)
     * 
     * - KICC V2 알리페이 플러스
     */
    BPI,
    /**
     * Boost
     * 
     * - KICC V2 알리페이 플러스
     */
    BOOST,
    /**
     * BillEase
     * 
     * - KICC V2 알리페이 플러스
     */
    BILL_EASE,
    /**
     * Tinaba
     * 
     * - KICC V2 알리페이 플러스
     */
    TINABA,
    /**
     * MPay
     * 
     * - KICC V2 알리페이 플러스
     */
    MPAY,
    /**
     * Kredivo
     * 
     * - KICC V2 알리페이 플러스
     */
    KREDIVO,
    /**
     * WeChat Pay
     * 
     * - KICC V2 알리페이 플러스
     */
    WECHAT;

    fun toJson(): String = name
}
