// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

/**
 * **무이자 할부를 적용할 PG사 구분코드**
 */
enum class FreeInstallmentPlanPgProvider {
    INICIS_V2,
    KCP_V2,
    KSNET,
    NICE_V2,
    TOSSPAYMENTS,
    WELCOME;

    fun toJson(): String = name
}
