// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity

/**
 * 구매자 성별
 */
enum class Gender {
    /**
     * 남성
     */
    MALE,
    /**
     * 여성
     */
    FEMALE,
    /**
     * 기타
     */
    OTHER;

    fun toJson(): String = name
}
