// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **결제창이 iframe 방식일 경우 결제창에 적용할 속성**
 */
@Parcelize
data class Iframe(
    /**
     * `false`로 설정하면 결제창 배경이 투명해집니다.
     */
    val dim: Boolean?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "dim" to dim?.let { dim }
    )
}
