// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **할부 개월 수 설정**
 * 
 * 할부 결제 시 할부 개월 수를 설정할 수 있습니다.
 * 
 * `fixedMonth`와 `availableMonthList` 중 하나만 제공해주세요.
 * 
 * - fixedMonth: 고정 할부 개월 수
 * - availableMonthList: 렌더링을 허용 할 할부 개월 수 리스트
 * 
 * 예1) 3개월 고정 할부 개월 수
 * 
 * ```js
 * monthOption: {
 * fixedMonth: 3
 * }
 * ```
 * 
 * 예2) 2, 3, 4, 5, 6개월 리스트 할부 개월 수
 * 
 * ```js
 * monthOption: {
 * availableMonthList: [2, 3, 4, 5, 6]
 * }
 * ```
 */
@Parcelize
sealed interface InstallmentMonthOption : Parcelable {
    /**
     * **구매자가 선택할 수 없도록 고정된 할부 개월수**
     * 
     * 구매자가 할부 개월 수를 선택할 수 있도록 하려면 `availableMonthList`를 사용해주세요.
     */
    @Parcelize
    data class FixedMonth(val value: Long) : InstallmentMonthOption
    /**
     * **구매자가 선택할 수 있는 할부 개월수 리스트**
     * 
     * 구매자가 할부 개월 수를 선택할 수 없도록 하려면 `fixedMonth`를 사용해주세요.
     */
    @Parcelize
    data class AvailableMonthList(val value: List<Long>) : InstallmentMonthOption

    fun toJson(): Map<String, Any> = when (this) {
        is FixedMonth -> mapOf("fixedMonth" to value)
        is AvailableMonthList -> mapOf("availableMonthList" to value)
    }
}
