// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity

enum class IssueBillingKeyUIType {
    PAYPAL_RT;

    fun toJson(): String = name
}
