// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import io.portone.sdk.android.type.entity.OfferPeriodRange
import kotlinx.parcelize.Parcelize

/**
 * **시작 시점만 있는 기간 범위**
 */
@Parcelize
data class OfferPeriodRangeFrom(
    /**
     * **시작 시점**
     */
    val from: String
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "from" to from
    )
}
