// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import io.portone.sdk.android.type.entity.OfferPeriodRange
import kotlinx.parcelize.Parcelize

/**
 * **시작 지점과 종료 지점이 모두 있는 기간 범위**
 */
@Parcelize
data class OfferPeriodRangeFromTo(
    /**
     * **시작 시점**
     */
    val from: String,
    /**
     * **종료 지점**
     */
    val to: String
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("from", from)
        put("to", to)
    }
}
