// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import io.portone.sdk.android.type.entity.OfferPeriodRangeFrom
import io.portone.sdk.android.type.entity.OfferPeriodRangeFromTo
import io.portone.sdk.android.type.entity.OfferPeriodRangeTo
import kotlinx.parcelize.Parcelize

/**
 * **기간 범위**
 */
private typealias _OfferPeriodRangeFrom = OfferPeriodRangeFrom
private typealias _OfferPeriodRangeTo = OfferPeriodRangeTo
private typealias _OfferPeriodRangeFromTo = OfferPeriodRangeFromTo

@Parcelize
sealed class OfferPeriodRange : Parcelable {
    @Parcelize
    data class OfferPeriodRangeFrom(val value: _OfferPeriodRangeFrom) : OfferPeriodRange()
    @Parcelize
    data class OfferPeriodRangeTo(val value: _OfferPeriodRangeTo) : OfferPeriodRange()
    @Parcelize
    data class OfferPeriodRangeFromTo(val value: _OfferPeriodRangeFromTo) : OfferPeriodRange()

    fun toJson(): Any = when (this) {
        is OfferPeriodRangeFrom -> value.toJson()
        is OfferPeriodRangeTo -> value.toJson()
        is OfferPeriodRangeFromTo -> value.toJson()
    }
}
