// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

enum class PaymentUIType {
    PAYPAL_SPB;

    fun toJson(): String = name
}
