// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **팝업 관련 필드**
 * 
 * UI가 팝업 창으로 열릴 때 적용되는 속성입니다.
 */
@Parcelize
data class Popup(
    /**
     * **팝업 정중앙 표시**
     * `true`로 설정하면 팝업이 브라우저 화면의 정중앙에 표시됩니다. 결제사 및 환경에 따라 적용되지 않을 수 있습니다.
     */
    val center: Boolean? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        center?.let { put("center", center) }
    }
}
