// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity

/**
 * **상품 유형**
 */
enum class ProductType {
    /**
     * 실물
     */
    REAL,
    /**
     * 디지털
     */
    DIGITAL;

    fun toJson(): String = name
}
