// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **구매 상품 상세 정보**
 */
@Parcelize
data class Product(
    /**
     * **상품 ID**
     */
    val id: String,
    /**
     * **상품명**
     */
    val name: String,
    /**
     * **상품 코드**
     * 
     * - 토스페이먼츠의 경우 필수로 입력해주세요.
     */
    val code: String?,
    /**
     * **상품 단위 가격**
     * 
     * 결제를 원하는 통화(currency)별 scale factor(소수점 몇번째 자리까지 유효한지)를 고려한 number 형식만 허용됩니다.
     * 
     * - 1000 만큼 원화(KRW) 결제를 하는 경우, scale factor가 0이기 때문에 **1000 \* (10의 0승) = 1000**을 전달해야 합니다.
     * - 1.50 만큼 달러(USD) 결제를 하는 경우, scale factor가 2이기 때문에 **1.50 \* (10의 2승) = 150**을 전달해야 합니다.
     * 
     * 이렇게 전달 된 값은 실제로 PG사에 결제를 요청할때 currency에 따라 올바른 값으로 변환되기 때문에 반드시 currency값을 필수로 입력해야 합니다.
     */
    val amount: Long,
    /**
     * **상품 수량**
     */
    val quantity: Long,
    /**
     * **상품 태그**
     */
    val tag: String?,
    /**
     * **상품 판매 URL**
     */
    val link: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("id", id)
        put("name", name)
        code?.let { put("code", code) }
        put("amount", amount)
        put("quantity", quantity)
        tag?.let { put("tag", tag) }
        link?.let { put("link", link) }
    }
}
