// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **구매 상품 상세 정보**
 */
@Parcelize
data class Product(
    /**
     * **상품 ID**
     */
    val id: String,
    /**
     * **상품명**
     */
    val name: String,
    /**
     * **상품 코드**
     */
    val code: String? = null,
    /**
     * **상품 단위 가격**
     * 
     * 상품의 단위당 가격을 정수로 나타냅니다.
     * 
     * 해외 통화의 경우 통화의 최소 단위(minor unit)를 기준으로 합니다. 예를 들어, USD의 최소 단위는 센트(0.01 USD)이므로, 6 USD의 경우 100배하여 600으로 입력합니다.
     * 
     * 최소 단위는 [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)에 표준화된 것을 기준으로 합니다.
     * 
     * - KRW: 1배
     * - USD: 100배
     * - JPY: 1배
     */
    val amount: Long,
    /**
     * **상품 수량**
     */
    val quantity: Long,
    /**
     * **상품 태그**
     */
    val tag: String? = null,
    /**
     * **상품 판매 URL**
     */
    val link: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("id", id)
        put("name", name)
        code?.let { put("code", code) }
        put("amount", amount)
        put("quantity", quantity)
        tag?.let { put("tag", tag) }
        link?.let { put("link", link) }
    }
}
