// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 상점 영업시간 (HH:mm)
 */
@Parcelize
data class StoreDetailsOpeningHours(
    /**
     * 영업 시작 시간
     */
    val `open`: String?,
    /**
     * 영업 종료 시간
     */
    val close: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        `open`?.let { put("open", `open`) }
        close?.let { put("close", close) }
    }
}
