// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity

import android.os.Parcelable
import io.portone.sdk.android.type.entity.StoreDetailsOpeningHours
import kotlinx.parcelize.Parcelize

/**
 * **상점 정보**
 * 
 * - KSNET 카카오페이의 경우 필수 입력
 * - 나이스페이먼츠의 경우 매출 전표에 표기 할 용도로 선택 입력
 * - KG이니시스 일본결제의 경우 JPPG(gmoPayment) 결제의 상점정보로 사용되거나 편의점 결제 시 영수증 표시 정보로 사용됨.
 */
@Parcelize
data class StoreDetails(
    /**
     * **대표자 이름**
     */
    val ceoFullName: String? = null,
    /**
     * **전화번호**
     */
    val phoneNumber: String? = null,
    /**
     * **주소**
     */
    val address: String? = null,
    /**
     * 우편번호
     */
    val zipcode: String? = null,
    /**
     * 이메일
     */
    val email: String? = null,
    /**
     * **사업자명 (상호)**
     */
    val businessName: String? = null,
    /**
     * **사업자 등록 번호**
     */
    val businessRegistrationNumber: String? = null,
    /**
     * **상점명**
     */
    val storeName: String? = null,
    /**
     * 상점명 약어
     */
    val storeNameShort: String? = null,
    /**
     * 상점명 영문
     */
    val storeNameEn: String? = null,
    /**
     * 상점명 후리카나 (일본어 읽는법 표기)
     */
    val storeNameKana: String? = null,
    /**
     * 상점 영업시간 (HH:mm)
     */
    val openingHours: StoreDetailsOpeningHours? = null,
    /**
     * **상점 연락처 정보 이름**
     * 
     * ex: 문의창구, 연락처, 지원창구
     */
    val contactName: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        ceoFullName?.let { put("ceoFullName", ceoFullName) }
        phoneNumber?.let { put("phoneNumber", phoneNumber) }
        address?.let { put("address", address) }
        zipcode?.let { put("zipcode", zipcode) }
        email?.let { put("email", email) }
        businessName?.let { put("businessName", businessName) }
        businessRegistrationNumber?.let { put("businessRegistrationNumber", businessRegistrationNumber) }
        storeName?.let { put("storeName", storeName) }
        storeNameShort?.let { put("storeNameShort", storeNameShort) }
        storeNameEn?.let { put("storeNameEn", storeNameEn) }
        storeNameKana?.let { put("storeNameKana", storeNameKana) }
        openingHours?.let { put("openingHours", openingHours.toJson()) }
        contactName?.let { put("contactName", contactName) }
    }
}
