// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity

enum class WindowType {
    IFRAME,
    POPUP,
    REDIRECTION,
    UI;

    fun toJson(): String = name
}
