// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2PayerAddress
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2PayerTaxInfo
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2Payer(
    /**
     * 구매자 정보
     */
    val taxInfo: PaypalV2PayerTaxInfo? = null,
    val address: PaypalV2PayerAddress? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        taxInfo?.let { put("tax_info", taxInfo.toJson()) }
        address?.let { put("address", address.toJson()) }
    }
}
