// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

/**
 * 버튼 렌더링 방향
 */
enum class PaypalV2StyleLayout {
    vertical,
    horizontal;

    fun toJson(): String = name
}
