// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

/**
 * 버튼 모양
 */
enum class PaypalV2StyleShape {
    rect,
    pill;

    fun toJson(): String = name
}
