// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.loadPaymentUI

import android.os.Parcelable
import io.portone.sdk.type.entity.Country
import kotlinx.parcelize.Parcelize

/**
 * 수령지 정보
 */
@Parcelize
data class PaypalV2PurchaseUnitShippingAddress(
    /**
     * 수령지 주소. 미 입력 시 입력된 주소로 override되지 않음
     */
    val addressLine1: String,
    val addressLine2: String?,
    val adminArea1: String?,
    /**
     * 필수 입력. 미 입력 시 create order 실패
     */
    val adminArea2: String,
    val postalCode: String?,
    /**
     * **국가**
     * 
     * [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
     */
    val countryCode: Country
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "address_line_1" to addressLine1,
        "address_line_2" to addressLine2?.let { addressLine2 },
        "admin_area_1" to adminArea1?.let { adminArea1 },
        "admin_area_2" to adminArea2,
        "postal_code" to postalCode?.let { postalCode },
        "country_code" to countryCode.toJson()
    )
}
