// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2AdditionalData
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2Payer
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2PurchaseUnit
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2Style
import kotlinx.parcelize.Parcelize

/**
 * **Paypal bypass 파라미터**
 */
@Parcelize
data class PaypalV2LoadPaymentUIBypass(
    /**
     * SPB 버튼 렌더링에 필요한 파라미터
     */
    val style: PaypalV2Style?,
    /**
     * 허용할 결제 수단 (예: "card, credit, bancontact")
     */
    val enableFunding: String?,
    /**
     * 차단할 결제 수단 (예: "venmo, mercadopago")
     */
    val disableFunding: String?,
    /**
     * create order API 호출에 필요한 파라미터
     */
    val purchaseUnits: List<PaypalV2PurchaseUnit>?,
    val payer: PaypalV2Payer?,
    /**
     * STC 파라미터
     */
    val additionalData: List<PaypalV2AdditionalData>?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        style?.let { put("style", style.toJson()) }
        enableFunding?.let { put("enable-funding", enableFunding) }
        disableFunding?.let { put("disable-funding", disableFunding) }
        purchaseUnits?.let { put("purchase_units", purchaseUnits.map { it.toJson() }) }
        payer?.let { put("payer", payer.toJson()) }
        additionalData?.let { put("additional_data", additionalData.map { it.toJson() }) }
    }
}
