// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2StyleColor
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2StyleLabel
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2StyleLayout
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2StyleShape
import kotlinx.parcelize.Parcelize

/**
 * SPB 버튼 렌더링에 필요한 파라미터
 */
@Parcelize
data class PaypalV2Style(
    /**
     * 버튼 색상
     */
    val color: PaypalV2StyleColor?,
    /**
     * 버튼 높이
     */
    val height: Long?,
    /**
     * 버튼 라벨
     */
    val label: PaypalV2StyleLabel?,
    /**
     * 버튼 렌더링 방향
     */
    val layout: PaypalV2StyleLayout?,
    /**
     * 버튼 모양
     */
    val shape: PaypalV2StyleShape?,
    /**
     * label이 installment일 때 할부 결제 되는 월
     */
    val period: String?,
    /**
     * 버튼 하위에 문구 노출 여부
     */
    val tagline: Boolean?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        color?.let { put("color", color.toJson()) }
        height?.let { put("height", height) }
        label?.let { put("label", label.toJson()) }
        layout?.let { put("layout", layout.toJson()) }
        shape?.let { put("shape", shape.toJson()) }
        period?.let { put("period", period) }
        tagline?.let { put("tagline", tagline) }
    }
}
