// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.Country
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2PayerAddress(
    /**
     * 구매자 주소지 정보
     */
    val addressLine1: String? = null,
    val addressLine2: String? = null,
    val adminArea1: String? = null,
    val adminArea2: String? = null,
    /**
     * 우편번호
     */
    val postalCode: String? = null,
    /**
     * **국가**
     * 
     * [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) 코드입니다.
     */
    val countryCode: Country
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        addressLine1?.let { put("address_line_1", addressLine1) }
        addressLine2?.let { put("address_line_2", addressLine2) }
        adminArea1?.let { put("admin_area_1", adminArea1) }
        adminArea2?.let { put("admin_area_2", adminArea2) }
        postalCode?.let { put("postal_code", postalCode) }
        put("country_code", countryCode.toJson())
    }
}
