// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadPaymentUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2PayerAddress
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2PayerTaxInfo
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2Payer(
    /**
     * 구매자 정보
     */
    val taxInfo: PaypalV2PayerTaxInfo?,
    val address: PaypalV2PayerAddress?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "tax_info" to taxInfo?.let { taxInfo.toJson() },
        "address" to address?.let { address.toJson() }
    )
}
