// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.response

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **리디렉션 없이 빌링키 발급 및 초회결제 UI가 표시된 경우 반환값**
 */
@Parcelize
data class IssueBillingKeyAndPayResponse(
    /**
     * `ISSUE_BILLING_KEY_AND_PAY`
     */
    val transactionType: String,
    /**
     * **빌링키**
     * 
     * 빌링결제를 일으킬 때 사용하는 빌링키입니다. 수동 승인 사용시 'NEEDS\_CONFIRMATION'으로 전달됩니다.
     */
    val billingKey: String,
    /**
     * 수동 승인 사용시 수동 승인 API 호출에 필요한 토큰입니다.
     */
    val billingIssueToken: String? = null,
    /**
     * **결제 ID**
     * 
     * 초회결제의 결제 ID입니다.
     */
    val paymentId: String,
    /**
     * **결제 시도 ID**
     * 
     * 초회결제에 해당하는, 요청마다 고유하게 생성되는 결제 시도 ID입니다. 수동 승인 사용시 'NEEDS\_CONFIRMATION'으로 전달됩니다.
     */
    val txId: String,
    /**
     * **오류 코드**
     * 
     * 실패한 경우 오류 코드입니다.
     */
    val code: String? = null,
    /**
     * **오류 메시지**
     * 
     * 실패한 경우 오류 메시지입니다.
     */
    val message: String? = null,
    /**
     * **PG 오류 코드**
     * 
     * PG에서 오류 코드를 내려 주는 경우 이 오류 코드를 그대로 반환합니다.
     */
    val pgCode: String? = null,
    /**
     * **PG 오류 메시지**
     * 
     * PG에서 오류 메시지를 내려 주는 경우 이 오류 메시지를 그대로 반환합니다.
     */
    val pgMessage: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("transactionType", transactionType)
        put("billingKey", billingKey)
        billingIssueToken?.let { put("billingIssueToken", billingIssueToken) }
        put("paymentId", paymentId)
        put("txId", txId)
        code?.let { put("code", code) }
        message?.let { put("message", message) }
        pgCode?.let { put("pgCode", pgCode) }
        pgMessage?.let { put("pgMessage", pgMessage) }
    }
}
