// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.response

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **리디렉션 없이 결제 UI가 표시된 경우 반환값**
 */
@Parcelize
data class PaymentResponse(
    /**
     * **유형**
     * 
     * 일반결제의 경우 무조건 `PAYMENT`로 전달됩니다.
     */
    val transactionType: String,
    /**
     * **결제 시도 ID**
     * 
     * 요청마다 고유하게 생성되는 결제 시도 ID입니다.
     */
    val txId: String,
    /**
     * **결제 ID**
     */
    val paymentId: String,
    /**
     * **오류 코드**
     * 
     * 실패한 경우 오류 코드입니다.
     */
    val code: String?,
    /**
     * **오류 메시지**
     * 
     * 실패한 경우 오류 메시지입니다.
     */
    val message: String?,
    /**
     * **PG 오류 코드**
     * 
     * PG에서 오류 코드를 내려 주는 경우 이 오류 코드를 그대로 반환합니다.
     */
    val pgCode: String?,
    /**
     * **PG 오류 메시지**
     * 
     * PG에서 오류 메시지를 내려 주는 경우 이 오류 메시지를 그대로 반환합니다.
     */
    val pgMessage: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("transactionType", transactionType)
        put("txId", txId)
        put("paymentId", paymentId)
        code?.let { put("code", code) }
        message?.let { put("message", message) }
        pgCode?.let { put("pgCode", pgCode) }
        pgMessage?.let { put("pgMessage", pgMessage) }
    }
}
