// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2AdditionalData
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2ShippingAddress
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2Style
import kotlinx.parcelize.Parcelize

/**
 * **Paypal bypass 파라미터**
 */
@Parcelize
data class PaypalV2LoadIssueBillingKeyUIBypass(
    /**
     * 페이팔 빌링키 발급 UI 호출 시 필요한 파라미터
     */
    val style: PaypalV2Style? = null,
    val shippingAddress: PaypalV2ShippingAddress? = null,
    /**
     * STC 파라미터
     */
    val additionalData: List<PaypalV2AdditionalData>? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        style?.let { put("style", style.toJson()) }
        shippingAddress?.let { put("shipping_address", shippingAddress.toJson()) }
        additionalData?.let { put("additional_data", additionalData.map { it.toJson() }) }
    }
}
