// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.loadIssueBillingKeyUI

import android.os.Parcelable
import io.portone.sdk.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2Country
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2ShippingAddress(
    /**
     * 수령인 이름
     */
    val recipientName: String?,
    /**
     * 도로명 주소
     */
    val line1: String,
    /**
     * 아파트 동 호수
     */
    val line2: String?,
    /**
     * 도시 이름
     */
    val city: String,
    /**
     * 주 이름 (아르헨티나, 브라질, 캐나다, 중국, 인도, 이탈리아, 일본, 멕시코, 태국 또는 미국의 경우 필수)
     */
    val state: String?,
    /**
     * 우편번호
     */
    val postalCode: String?,
    /**
     * **페이팔 V2 국가 코드**
     */
    val countryCode: PaypalV2Country
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "recipient_name" to recipientName?.let { recipientName },
        "line1" to line1,
        "line2" to line2?.let { line2 },
        "city" to city,
        "state" to state?.let { state },
        "postal_code" to postalCode?.let { postalCode },
        "country_code" to countryCode.toJson()
    )
}
