// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI

/**
 * 버튼 색상
 */
enum class PaypalV2StyleColor {
    gold,
    blue,
    silver,
    white,
    black;

    fun toJson(): String = name
}
