// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2Country
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2ShippingAddress(
    /**
     * 수령인 이름
     */
    val recipientName: String? = null,
    /**
     * 도로명 주소
     */
    val line1: String,
    /**
     * 아파트 동 호수
     */
    val line2: String? = null,
    /**
     * 도시 이름
     */
    val city: String,
    /**
     * 주 이름 (아르헨티나, 브라질, 캐나다, 중국, 인도, 이탈리아, 일본, 멕시코, 태국 또는 미국의 경우 필수)
     */
    val state: String? = null,
    /**
     * 우편번호
     */
    val postalCode: String? = null,
    /**
     * **페이팔 V2 국가 코드**
     */
    val countryCode: PaypalV2Country
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        recipientName?.let { put("recipient_name", recipientName) }
        put("line1", line1)
        line2?.let { put("line2", line2) }
        put("city", city)
        state?.let { put("state", state) }
        postalCode?.let { put("postal_code", postalCode) }
        put("country_code", countryCode.toJson())
    }
}
