// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.loadIssueBillingKeyUI

/**
 * 버튼 라벨
 */
enum class PaypalV2StyleLabel {
    paypal,
    checkout,
    buynow,
    pay,
    installment,
    subscribe,
    donate;

    fun toJson(): String = name
}
