// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2StyleColor
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2StyleLabel
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2StyleLayout
import io.portone.sdk.android.type.entity.bypass.loadIssueBillingKeyUI.PaypalV2StyleShape
import kotlinx.parcelize.Parcelize

/**
 * 페이팔 빌링키 발급 UI 호출 시 필요한 파라미터
 */
@Parcelize
data class PaypalV2Style(
    /**
     * 버튼 색상
     */
    val color: PaypalV2StyleColor? = null,
    /**
     * 버튼 높이
     */
    val height: Long? = null,
    /**
     * 버튼 라벨
     */
    val label: PaypalV2StyleLabel? = null,
    /**
     * 버튼 렌더링 방향
     */
    val layout: PaypalV2StyleLayout? = null,
    /**
     * 버튼 모양
     */
    val shape: PaypalV2StyleShape? = null,
    /**
     * 버튼 하위에 문구 노출 여부
     */
    val tagline: Boolean? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        color?.let { put("color", color.toJson()) }
        height?.let { put("height", height) }
        label?.let { put("label", label.toJson()) }
        layout?.let { put("layout", layout.toJson()) }
        shape?.let { put("shape", shape.toJson()) }
        tagline?.let { put("tagline", tagline) }
    }
}
