// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.issueBillingKeyAndPay

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.issueBillingKeyAndPay.EximbayV2BillTo
import io.portone.sdk.android.type.entity.bypass.issueBillingKeyAndPay.EximbayV2Merchant
import io.portone.sdk.android.type.entity.bypass.issueBillingKeyAndPay.EximbayV2Payment
import io.portone.sdk.android.type.entity.bypass.issueBillingKeyAndPay.EximbayV2ShipTo
import io.portone.sdk.android.type.entity.bypass.issueBillingKeyAndPay.EximbayV2Surcharge
import kotlinx.parcelize.Parcelize

/**
 * **엑심베이 bypass 파라미터**
 */
@Parcelize
data class EximbayV2IssueBillingKeyAndPayBypass(
    /**
     * 결제 정보
     */
    val payment: EximbayV2Payment? = null,
    val merchant: EximbayV2Merchant? = null,
    /**
     * **최대 3개의 추가 비용 목록**
     */
    val surcharge: List<EximbayV2Surcharge>? = null,
    /**
     * **배송지 정보**
     */
    val shipTo: EximbayV2ShipTo? = null,
    /**
     * **청구지 정보**
     */
    val billTo: EximbayV2BillTo? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        payment?.let { put("payment", payment.toJson()) }
        merchant?.let { put("merchant", merchant.toJson()) }
        surcharge?.let { put("surcharge", surcharge.map { it.toJson() }) }
        shipTo?.let { put("shipTo", shipTo.toJson()) }
        billTo?.let { put("billTo", billTo.toJson()) }
    }
}
