// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.issueBillingKeyAndPay

import android.os.Parcelable
import io.portone.sdk.type.entity.bypass.issueBillingKeyAndPay.EximbayV2BillTo
import io.portone.sdk.type.entity.bypass.issueBillingKeyAndPay.EximbayV2Merchant
import io.portone.sdk.type.entity.bypass.issueBillingKeyAndPay.EximbayV2Payment
import io.portone.sdk.type.entity.bypass.issueBillingKeyAndPay.EximbayV2ShipTo
import io.portone.sdk.type.entity.bypass.issueBillingKeyAndPay.EximbayV2Surcharge
import kotlinx.parcelize.Parcelize

/**
 * **엑심베이 bypass 파라미터**
 */
@Parcelize
data class EximbayV2IssueBillingKeyAndPayBypass(
    /**
     * 결제 정보
     */
    val payment: EximbayV2Payment?,
    val merchant: EximbayV2Merchant?,
    /**
     * **최대 3개의 추가 비용 목록**
     */
    val surcharge: List<EximbayV2Surcharge>?,
    /**
     * **배송지 정보**
     */
    val shipTo: EximbayV2ShipTo?,
    /**
     * **청구지 정보**
     */
    val billTo: EximbayV2BillTo?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "payment" to payment?.let { payment.toJson() },
        "merchant" to merchant?.let { merchant.toJson() },
        "surcharge" to surcharge?.let { surcharge.map { it.toJson() } },
        "shipTo" to shipTo?.let { shipTo.toJson() },
        "billTo" to billTo?.let { billTo.toJson() }
    )
}
