// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.issueBillingKey

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **갤럭시아 bypass 파라미터**
 */
@Parcelize
data class GalaxiaIssueBillingKeyBypass(
    /**
     * 구매 상품 코드
     */
    val itemCode: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        itemCode?.let { put("ITEM_CODE", itemCode) }
    }
}
