// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.issueBillingKey

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **네이버페이 bypass 파라미터**
 */
@Parcelize
data class NaverpayIssueBillingKeyBypass(
    /**
     * 하부 가맹점 명
     */
    val subMerchantName: String?,
    /**
     * 하부 가맹점 ID
     */
    val subMerchantId: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        subMerchantName?.let { put("subMerchantName", subMerchantName) }
        subMerchantId?.let { put("subMerchantId", subMerchantId) }
    }
}
