// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.issueBillingKey

/**
 * UI 스타일(기본: RED)
 */
enum class SmartroV2SkinColor {
    RED,
    GREEN,
    BLUE,
    PURPLE;

    fun toJson(): String = name
}
