// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.issueBillingKey

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **토스페이 bypass 파라미터**
 */
@Parcelize
data class TosspayV2IssueBillingKeyBypass(
    /**
     * 암호화된 사용자 CI
     */
    val encryptedUserCi: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        encryptedUserCi?.let { put("encryptedUserCi", encryptedUserCi) }
    }
}
