// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.issueBillingKey

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * **웰컴페이먼츠 bypass 파라미터**
 */
@Parcelize
data class WelcomeIssueBillingKeyBypass(
    /**
     * 메인 로고 URL (크기: 89x19)
     */
    val logoUrl: String? = null,
    /**
     * 서브 로고 URL (크기: 64x13)
     */
    val logo2Nd: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        logoUrl?.let { put("logo_url", logoUrl) }
        logo2Nd?.let { put("logo_2nd", logo2Nd) }
    }
}
