// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

/**
 * 현금영수증 발급 여부
 */
enum class EximbayV2TaxReceiptStatus {
    Y,
    N;

    fun toJson(): String = name
}
