// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 상점 정보
 */
@Parcelize
data class EximbayV2Merchant(
    /**
     * 상점명
     */
    val shop: String?,
    /**
     * 파트너 코드
     */
    val partnerCode: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        shop?.let { put("shop", shop) }
        partnerCode?.let { put("partner_code", partnerCode) }
    }
}
