// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2TaxReceiptStatus
import kotlinx.parcelize.Parcelize

/**
 * 세금 정보
 */
@Parcelize
data class EximbayV2Tax(
    /**
     * 현금영수증 발급 여부
     */
    val receiptStatus: EximbayV2TaxReceiptStatus? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        receiptStatus?.let { put("receipt_status", receiptStatus.toJson()) }
    }
}
