// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2BillTo
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2Merchant
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2Payment
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2Settings
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2ShipTo
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2Surcharge
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2Tax
import kotlinx.parcelize.Parcelize

/**
 * 엑심베이 V2 bypass 파라미터
 */
@Parcelize
data class EximbayV2Bypass(
    /**
     * 결제 정보
     */
    val payment: EximbayV2Payment? = null,
    /**
     * 상점 정보
     */
    val merchant: EximbayV2Merchant? = null,
    /**
     * 세금 정보
     */
    val tax: EximbayV2Tax? = null,
    /**
     * 최대 3개의 추가 비용 목록
     */
    val surcharge: List<EximbayV2Surcharge>? = null,
    /**
     * 배송지 정보
     */
    val shipTo: EximbayV2ShipTo? = null,
    /**
     * 청구지 정보
     */
    val billTo: EximbayV2BillTo? = null,
    /**
     * 설정 정보
     */
    val settings: EximbayV2Settings? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        payment?.let { put("payment", payment.toJson()) }
        merchant?.let { put("merchant", merchant.toJson()) }
        tax?.let { put("tax", tax.toJson()) }
        surcharge?.let { put("surcharge", surcharge.map { it.toJson() }) }
        shipTo?.let { put("ship_to", shipTo.toJson()) }
        billTo?.let { put("bill_to", billTo.toJson()) }
        settings?.let { put("settings", settings.toJson()) }
    }
}
