// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 결제 정보
 */
@Parcelize
data class EximbayV2Payment(
    /**
     * 결제수단 단독 노출
     */
    val paymentMethod: String?,
    /**
     * 결제수단 노출 목록
     */
    val multiPaymentMethod: List<String>?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        paymentMethod?.let { put("payment_method", paymentMethod) }
        multiPaymentMethod?.let { put("multi_payment_method", multiPaymentMethod) }
    }
}
