// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

/**
 * 인앱 웹뷰 여부
 */
enum class EximbayV2SettingsCallFromApp {
    Y,
    N;

    fun toJson(): String = name
}
