// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class EximbayV2Surcharge(
    /**
     * 항목명
     */
    val name: String?,
    /**
     * 수량
     */
    val quantity: String?,
    /**
     * 단가 (음수 가능)
     */
    val unitPrice: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        name?.let { put("name", name) }
        quantity?.let { put("quantity", quantity) }
        unitPrice?.let { put("unit_price", unitPrice) }
    }
}
