// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.EximbayV2SettingsCallFromApp
import kotlinx.parcelize.Parcelize

/**
 * 설정 정보
 */
@Parcelize
data class EximbayV2Settings(
    /**
     * 인앱 웹뷰 여부
     */
    val callFromApp: EximbayV2SettingsCallFromApp? = null,
    /**
     * 해외 결제 가맹점에서 국내 결제를 사용할 경우 `KR`
     */
    val issuerCountry: String? = null,
    /**
     * 입금 만료 일자 (yyyyMMddHH)
     */
    val virtualaccountExpiryDate: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        callFromApp?.let { put("call_from_app", callFromApp.toJson()) }
        issuerCountry?.let { put("issuer_country", issuerCountry) }
        virtualaccountExpiryDate?.let { put("virtualaccount_expiry_date", virtualaccountExpiryDate) }
    }
}
