// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.InicisJpPaymentUI
import kotlinx.parcelize.Parcelize

/**
 * 이니시스 일본 bypass 파라미터
 */
@Parcelize
data class InicisJpBypass(
    /**
     * 결제창 UI 설정
     */
    val paymentUi: InicisJpPaymentUI?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        paymentUi?.let { put("paymentUI", paymentUi.toJson()) }
    }
}
