// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 카카오페이 bypass 파라미터
 */
@Parcelize
data class KakaopayPaymentBypass(
    /**
     * 카카오페이 결제창에 띄워줄 사용자 정의 문구
     */
    val customMessage: String?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "custom_message" to customMessage?.let { customMessage }
    )
}
