// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.KcpV2ComplexPnt
import io.portone.sdk.android.type.entity.bypass.payment.KcpV2DispTax
import kotlinx.parcelize.Parcelize

/**
 * NHN KCP bypass 파라미터
 */
@Parcelize
data class KcpV2Bypass(
    val skinIndx: String? = null,
    val siteLogo: String? = null,
    val shopUserId: String,
    val kcpPayTitle: String? = null,
    /**
     * 포인트 결제의 경우 신용카드 + 포인트 결제인데, N으로 설정 시 포인트로만 결제가 이루어짐
     */
    val complexPntYn: KcpV2ComplexPnt? = null,
    val ptMemcorpCd: String? = null,
    /**
     * 가상계좌, 계좌이체 시 현금영수증 노출 여부
     */
    val dispTaxYn: KcpV2DispTax? = null,
    /**
     * 결제창에 노출될 고객사 상호명
     */
    val siteName: String? = null,
    /**
     * 에스크로 배송 예상 소요일
     */
    val deliTerm: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        skinIndx?.let { put("skin_indx", skinIndx) }
        siteLogo?.let { put("site_logo", siteLogo) }
        put("shop_user_id", shopUserId)
        kcpPayTitle?.let { put("kcp_pay_title", kcpPayTitle) }
        complexPntYn?.let { put("complex_pnt_yn", complexPntYn.toJson()) }
        ptMemcorpCd?.let { put("pt_memcorp_cd", ptMemcorpCd) }
        dispTaxYn?.let { put("disp_tax_yn", dispTaxYn.toJson()) }
        siteName?.let { put("site_name", siteName) }
        deliTerm?.let { put("deli_term", deliTerm) }
    }
}
