// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

/**
 * 가상계좌, 계좌이체 시 현금영수증 노출 여부
 */
enum class KcpV2DispTax {
    Y,
    N,
    R,
    E;

    fun toJson(): String = name
}
