// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.KpnCardSelect
import kotlinx.parcelize.Parcelize

/**
 * KPN bypass 파라미터
 */
@Parcelize
data class KpnBypass(
    /**
     * - 해외카드 (VISA + MASTER + JCB) : `GLOBAL`
     * - 11Pay (SKPay) : `11PAY`
     * - 구인증 : `LEGACY_AUTH`
     * - 키인 : `KEY_IN`
     */
    val cardSelect: List<KpnCardSelect>?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        cardSelect?.let { put("CardSelect", cardSelect.map { it.toJson() }) }
    }
}
