// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

enum class KpnCardSelect {
    /**
     * 해외카드
     */
    GLOBAL,
    /**
     * 11Pay
     */
    _11PAY,
    /**
     * 구인증
     */
    LEGACY_AUTH,
    /**
     * 키인
     */
    KEY_IN;

    fun toJson(): String = when (this) {
        GLOBAL -> "GLOBAL"
        _11PAY -> "11PAY"
        LEGACY_AUTH -> "LEGACY_AUTH"
        KEY_IN -> "KEY_IN"
    }
}
