// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

/**
 * 카드 결제창에서 카카오페이 결제시 허용할 결제수단
 */
enum class KsnetSndKakaopayType {
    /**
     * 카드 결제만 허용
     */
    CARD,
    /**
     * 카카오머니 결제만 허용
     */
    MONEY;

    fun toJson(): String = name
}
