// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

/**
 * 간편 결제 표시 구분
 */
enum class KsnetSndQpayType {
    /**
     * 간편 결제 표시
     */
    _1,
    /**
     * 간편 결제 미표시
     */
    _0;

    fun toJson(): String = when (this) {
        _1 -> "1"
        _0 -> "0"
    }
}
