// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

/**
 * 간편 결제 표시 구분
 */
enum class KsnetSndQpayType {
    /**
     * 간편 결제 표시
     */
    Y,
    /**
     * 간편 결제 미표시
     */
    N;

    fun toJson(): String = name
}
