// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.KsnetSndQpayType
import kotlinx.parcelize.Parcelize

/**
 * KSNET bypass 파라미터
 */
@Parcelize
data class KsnetPaymentBypass(
    /**
     * 간편 결제 표시 구분
     */
    val sndQpayType: KsnetSndQpayType?,
    /**
     * **KSNET 간편결제 다이렉트 여부**
     */
    val easyPayDirect: Boolean?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        sndQpayType?.let { put("sndQpayType", sndQpayType.toJson()) }
        easyPayDirect?.let { put("easyPayDirect", easyPayDirect) }
    }
}
