// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 추가 설정 옵션
 */
@Parcelize
data class MobiliansV2HiddenOptions(
    /**
     * 결제창 하단안내문구영역 숨김 여부
     * 
     * - `Y`: 숨김
     * - `N`: 노출 (default)
     */
    val infoArea: String? = null,
    /**
     * 결제창 footer영역 숨김 여부
     * 
     * - `Y`: 숨김
     * - `N`: 노출 (default)
     */
    val footerArea: String? = null,
    /**
     * 결제창 상품정보영역 숨김 여부
     * 
     * - `Y`: 숨김
     * - `N`: 노출 (default)
     */
    val productArea: String? = null,
    /**
     * 결제창 이메일입력영역 숨김 여부
     * 
     * - `Y`: 숨김
     * - `N`: 노출 (default)
     */
    val emailArea: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        infoArea?.let { put("info_area", infoArea) }
        footerArea?.let { put("footer_area", footerArea) }
        productArea?.let { put("product_area", productArea) }
        emailArea?.let { put("email_area", emailArea) }
    }
}
