// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 결제 수단 별 bypass할 값
 */
@Parcelize
data class MobiliansV2PayOptions(
    /**
     * 우리카드 우리페이(WON카드, WON뱅킹) 결제만 제공할지 여부
     * 
     * - `Y`: 사용
     * - `N`: 미사용
     */
    val cnPayAppUseYn: String? = null,
    /**
     * 우리카드 우리페이 결제수단 목록 WON카드, WON뱅킹에서 단독으로 결제할지 여부
     * (cn\_pay\_app\_use\_yn이 "Y"이어야 사용가능)
     * 
     * - `01`: WON카드
     * - `02`: WON뱅킹
     */
    val cnPayAppUseCd: String? = null,
    /**
     * 간편결제 다이렉트 호출 시 사용할 결제수단
     * 
     * - `C`: 카드
     * - `P`: 네이버페이 포인트 (네이버페이에서만 사용 가능)
     * - `M`: 카카오페이 머니, 토스머니 (카카오페이, 토스페이에서만 사용 가능)
     */
    val epPayType: String? = null,
    /**
     * 휴대폰 결제창에서 휴대폰 번호를 고정할지 여부
     * 
     * - `Y`: 고정 사용
     * - `N`: 미사용
     */
    val mcFixNo: String? = null,
    /**
     * 휴대폰 결제에서 ARS 인증 사용 여부
     * 
     * - `SAFECALL`: 고정 사용
     */
    val mcSafeCall: String? = null,
    /**
     * 휴대폰 결제에서 간소화 결제 미사용 여부
     * 
     * - `Y`: 간소화 결제 미사용
     */
    val mcSimplePay: String? = null,
    /**
     * 계좌이체 결제에서 에스크로 구매 비밀먼호
     * (에스크로 적용하여 뱅크페이 다이렉트 호출 시 필수 입력)
     */
    val raEscrowPassword: String? = null,
    /**
     * 계좌이체 결제에서 뱅크페이 다이렉트 호출 여부
     * 
     * - `Y`: 사용
     * - `N`: 미사용
     */
    val raDirect: String? = null,
    /**
     * 가상계좌 결제창에서 현금영수증 발급 항목 노출 여부
     * 
     * - `Y`: 노출
     * - `N`: 미노출
     */
    val vaCashReceipt: String? = null,
    /**
     * 가상계좌 결제창에서 에스크로 사용 설정 항목 노출 여부
     * 
     * - `Y`: 노출
     * - `N`: 미노출
     */
    val vaEscrow: String? = null,
    /**
     * 가상계좌 결제창에서 이메일 입력 필수 여부
     * 
     * - `Y`: 필수 입력
     * - `N`: 선택 입력
     */
    val vaEmail: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        cnPayAppUseYn?.let { put("cn_pay_app_use_yn", cnPayAppUseYn) }
        cnPayAppUseCd?.let { put("cn_pay_app_use_cd", cnPayAppUseCd) }
        epPayType?.let { put("ep_pay_type", epPayType) }
        mcFixNo?.let { put("mc_fix_no", mcFixNo) }
        mcSafeCall?.let { put("mc_safe_call", mcSafeCall) }
        mcSimplePay?.let { put("mc_simple_pay", mcSimplePay) }
        raEscrowPassword?.let { put("ra_escrow_password", raEscrowPassword) }
        raDirect?.let { put("ra_direct", raDirect) }
        vaCashReceipt?.let { put("va_cash_receipt", vaCashReceipt) }
        vaEscrow?.let { put("va_escrow", vaEscrow) }
        vaEmail?.let { put("va_email", vaEmail) }
    }
}
