// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.MobiliansV2HiddenOptions
import io.portone.sdk.android.type.entity.bypass.payment.MobiliansV2PayOptions
import kotlinx.parcelize.Parcelize

/**
 * 모빌리언스 V2 bypass 파라미터
 */
@Parcelize
data class MobiliansV2Bypass(
    /**
     * 담당자 이메일 (결제 결과 노티 실패 또는 입금 완료 시 알림이 발송될 이메일)
     */
    val notiEmail: String? = null,
    /**
     * 고객사 로고 표기 여부
     * 
     * - `Y`: 표기 (사전 협의 된 이미지 등록 필요)
     * - `N`: 미표기
     */
    val cpLogo: String? = null,
    /**
     * 법인 단위 로고 표기 여부
     * 
     * - `Y`: 표기 (사전 협의 된 이미지 등록 필요)
     * - `N`: 미표기
     */
    val entpLogo: String? = null,
    /**
     * 결제창 색상 설정 (HTML 색상코드)
     * ex) #006EB9
     */
    val cssType: String? = null,
    /**
     * 고객사 UI 설정
     */
    val cpUi: String? = null,
    /**
     * 결제 수단 별 bypass할 값
     */
    val payOptions: MobiliansV2PayOptions? = null,
    /**
     * 추가 설정 옵션
     */
    val hiddenOptions: MobiliansV2HiddenOptions? = null,
    /**
     * 상품권 결제창 고객사 로고 표시 여부
     * 
     * - `Y`: 표시 (사전 협의 된 이미지 등록 필요)
     * - `N`: 미표시, 모빌리언스 로고 표시 (default)
     */
    val logoYn: String? = null,
    /**
     * 상품권 결제창 안내문영역 노출 여부
     * 
     * - `Y`: 표시 (default)
     * - `N`: 미표시
     */
    val infoareaYn: String? = null,
    /**
     * 상품권 결제창 하단 안내영역 노출 여부
     * 
     * - `Y`: 표시 (default)
     * - `N`: 미표시
     */
    val footerYn: String? = null,
    /**
     * 상품권 결제창 이용약관영역 노출 여부
     * 
     * - `Y`: 노출 (default)
     * - `N`: 숨김
     */
    val contractHidden: String? = null,
    /**
     * 상품권 결제창 이메일입력영역 숨김 여부
     * 
     * - `Y`: 숨김
     * - `N`: 노출 (default)
     */
    val emailHidden: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        notiEmail?.let { put("noti_email", notiEmail) }
        cpLogo?.let { put("cp_logo", cpLogo) }
        entpLogo?.let { put("entp_logo", entpLogo) }
        cssType?.let { put("css_type", cssType) }
        cpUi?.let { put("cp_ui", cpUi) }
        payOptions?.let { put("pay_options", payOptions.toJson()) }
        hiddenOptions?.let { put("hidden_options", hiddenOptions.toJson()) }
        logoYn?.let { put("LOGO_YN", logoYn) }
        infoareaYn?.let { put("INFOAREA_YN", infoareaYn) }
        footerYn?.let { put("FOOTER_YN", footerYn) }
        contractHidden?.let { put("CONTRACT_HIDDEN", contractHidden) }
        emailHidden?.let { put("EMAIL_HIDDEN", emailHidden) }
    }
}
