// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.NaverpayProductItemPayReferrer
import kotlinx.parcelize.Parcelize

@Parcelize
data class NaverpayProductItem(
    /**
     * 결제 상품 유형
     */
    val categoryType: String,
    /**
     * 결제 상품 분류
     */
    val categoryId: String,
    /**
     * 결제 상품 식별값
     */
    val uid: String,
    /**
     * 상품명
     */
    val name: String,
    /**
     * 결제 상품 유입경로
     */
    val payReferrer: NaverpayProductItemPayReferrer? = null,
    /**
     * 시작일(YYYYMMDD)
     */
    val startDate: String? = null,
    /**
     * 종료일(YYYYMMDD)
     */
    val endDate: String? = null,
    /**
     * 하위 판매자 식별키
     */
    val sellerId: String? = null,
    /**
     * 결제 상품 개수
     */
    val count: Long
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("categoryType", categoryType)
        put("categoryId", categoryId)
        put("uid", uid)
        put("name", name)
        payReferrer?.let { put("payReferrer", payReferrer.toJson()) }
        startDate?.let { put("startDate", startDate) }
        endDate?.let { put("endDate", endDate) }
        sellerId?.let { put("sellerId", sellerId) }
        put("count", count)
    }
}
