// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.NaverpayProductItem
import io.portone.sdk.android.type.entity.bypass.payment.NaverpaySubMerchantInfo
import kotlinx.parcelize.Parcelize

/**
 * 네이버페이 bypass 파라미터
 */
@Parcelize
data class NaverpayPaymentBypass(
    /**
     * 이용 완료일(YYYYMMDD)
     */
    val useCfmYmdt: String?,
    val productItems: List<NaverpayProductItem>,
    /**
     * 하부 가맹점 정보. PG 업종 가맹점인 경우에만 필수 값
     */
    val subMerchantInfo: NaverpaySubMerchantInfo?,
    /**
     * 배송비
     */
    val deliveryFee: Long?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        useCfmYmdt?.let { put("useCfmYmdt", useCfmYmdt) }
        put("productItems", productItems.map { it.toJson() })
        subMerchantInfo?.let { put("subMerchantInfo", subMerchantInfo.toJson()) }
        deliveryFee?.let { put("deliveryFee", deliveryFee) }
    }
}
