// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

/**
 * 결제 상품 유입경로
 */
enum class NaverpayProductItemPayReferrer {
    NAVER_BOOK,
    NAVER_MUSIC,
    NAVER_SHOPPING,
    NAVER_MAP,
    NAVER_PLACE,
    SEARCH_AD,
    NAVER_SEARCH,
    BRAND_SEARCH,
    PARTNER_DIRECT,
    ETC;

    fun toJson(): String = name
}
