// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

/**
 * 결제창 스크롤 미사용 여부 (PC Only, Y: 미사용 / N(default): 사용)
 */
enum class NiceV2DisableScroll {
    Y,
    N;

    fun toJson(): String = name
}
