// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

/**
 * 다이렉트 호출 결제 수단 (BANK: 계좌이체/CELLPHONE: 휴대폰 소액결제)
 */
enum class NiceV2DirectShow {
    /**
     * 계좌이체
     */
    BANK,
    /**
     * 휴대폰 소액결제
     */
    CELLPHONE;

    fun toJson(): String = name
}
