// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Paymentwall bypass 파라미터
 */
@Parcelize
data class PaymentwallBypass(
    /**
     * **위젯 코드**
     */
    val widget: String? = null,
    /**
     * **결제수단 코드**
     */
    val ps: String? = null,
    /**
     * **국가 코드 (ISO 3166 두 자리)**
     */
    val countryCode: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        widget?.let { put("widget", widget) }
        ps?.let { put("ps", ps) }
        countryCode?.let { put("country_code", countryCode) }
    }
}
