// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentSourcePaypal
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2PaymentSource(
    val paypal: PaypalV2PaymentSourcePaypal?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        paypal?.let { put("paypal", paypal.toJson()) }
    }
}
