// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentSourcePaypalExperienceContextLandingPage
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentSourcePaypalExperienceContextShippingPreference
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2PaymentSourcePaypalExperienceContext(
    val brandName: String? = null,
    val shippingPreference: PaypalV2PaymentSourcePaypalExperienceContextShippingPreference? = null,
    val landingPage: PaypalV2PaymentSourcePaypalExperienceContextLandingPage? = null,
    val paymentMethodPreference: PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        brandName?.let { put("brand_name", brandName) }
        shippingPreference?.let { put("shipping_preference", shippingPreference.toJson()) }
        landingPage?.let { put("landing_page", landingPage.toJson()) }
        paymentMethodPreference?.let { put("payment_method_preference", paymentMethodPreference.toJson()) }
    }
}
