// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

enum class PaypalV2PaymentSourcePaypalExperienceContextShippingPreference {
    GET_FROM_FILE,
    NO_SHIPPING,
    SET_PROVIDED_ADDRESS;

    fun toJson(): String = name
}
