// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2AdditionalData
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2Payer
import io.portone.sdk.android.type.entity.bypass.loadPaymentUI.PaypalV2PurchaseUnit
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentSource
import kotlinx.parcelize.Parcelize

/**
 * **Paypal bypass 파라미터**
 */
@Parcelize
data class PaypalV2PaymentBypass(
    /**
     * create order API 호출에 필요한 파라미터
     */
    val purchaseUnits: List<PaypalV2PurchaseUnit>?,
    val payer: PaypalV2Payer?,
    val paymentSource: PaypalV2PaymentSource?,
    /**
     * STC 파라미터
     */
    val additionalData: List<PaypalV2AdditionalData>?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        purchaseUnits?.let { put("purchase_units", purchaseUnits.map { it.toJson() }) }
        payer?.let { put("payer", payer.toJson()) }
        paymentSource?.let { put("payment_source", paymentSource.toJson()) }
        additionalData?.let { put("additional_data", additionalData.map { it.toJson() }) }
    }
}
