// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

enum class PaypalV2PaymentSourcePaypalExperienceContextPaymentMethodPreference {
    UNRESTRICTED,
    IMMEDIATE_PAYMENT_REQUIRED;

    fun toJson(): String = name
}
