// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.PaypalV2PaymentSourcePaypalExperienceContext
import kotlinx.parcelize.Parcelize

@Parcelize
data class PaypalV2PaymentSourcePaypal(
    val experienceContext: PaypalV2PaymentSourcePaypalExperienceContext? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        experienceContext?.let { put("experience_context", experienceContext.toJson()) }
    }
}
