// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.SmartroV2OpenType
import io.portone.sdk.android.type.entity.bypass.payment.SmartroV2SkinColor
import kotlinx.parcelize.Parcelize

/**
 * 스마트로 V2 bypass 파라미터
 */
@Parcelize
data class SmartroV2PaymentBypass(
    /**
     * 결제 상품 품목 개수
     */
    val goodsCnt: Long?,
    /**
     * UI 스타일 (기본값: `"RED"`)
     * 
     * `"RED"`, `"GREEN"`, `"BLUE"`, `"PURPLE"` 중 하나의 값으로 입력해주세요.
     */
    val skinColor: SmartroV2SkinColor?,
    /**
     * 해외 카드만 결제를 허용할지 여부(기본값: `"KR"`)
     * 
     * `"KR"`, `"EN"` 중 하나의 값으로 입력해주세요.
     */
    val openType: SmartroV2OpenType?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        goodsCnt?.let { put("GoodsCnt", goodsCnt) }
        skinColor?.let { put("SkinColor", skinColor.toJson()) }
        openType?.let { put("OpenType", openType.toJson()) }
    }
}
