// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsUiPromotionSectionDescription
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsUiPromotionSectionSummary
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayWidgetOptionsUiPromotionSection(
    val summary: TossBrandpayWidgetOptionsUiPromotionSectionSummary?,
    val description: TossBrandpayWidgetOptionsUiPromotionSectionDescription?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "summary" to summary?.let { summary.toJson() },
        "description" to description?.let { description.toJson() }
    )
}
