// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsUiPromotionSectionDescription
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsUiPromotionSectionSummary
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayWidgetOptionsUiPromotionSection(
    val summary: TossBrandpayWidgetOptionsUiPromotionSectionSummary? = null,
    val description: TossBrandpayWidgetOptionsUiPromotionSectionDescription? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        summary?.let { put("summary", summary.toJson()) }
        description?.let { put("description", description.toJson()) }
    }
}
