// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TosspayV2CashReceiptTradeOption
import kotlinx.parcelize.Parcelize

/**
 * 토스페이 bypass 파라미터
 */
@Parcelize
data class TosspayV2PaymentBypass(
    /**
     * 결제 만료 기한 (yyyy-MM-dd HH:mm:ss)
     */
    val expiredTime: String? = null,
    /**
     * 현금영수증 발급타입
     * 
     * - CULTURE: 문화비
     * - GENERAL: 일반 (기본값)
     * - PUBLIC\_TP: 교통비
     */
    val cashReceiptTradeOption: TosspayV2CashReceiptTradeOption? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        expiredTime?.let { put("expiredTime", expiredTime) }
        cashReceiptTradeOption?.let { put("cashReceiptTradeOption", cashReceiptTradeOption.toJson()) }
    }
}
