// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

/**
 * 버튼 스타일
 * 
 * - default(기본값): 모서리가 둥글고 주변에 여백을 가진 버튼
 * - full: 하단 영역이 전부 채워지는 형태의 버튼
 */
enum class TossBrandpayBrandpayOptionsUiButtonStyle {
    /**
     * 모서리가 둥글고 주변에 여백을 가진 버튼(기본값)
     */
    default,
    /**
     * 하단 영역이 전부 채워지는 형태의 버튼
     */
    full;

    fun toJson(): String = name
}
