// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TosspaymentsPaypalShippingAddress
import kotlinx.parcelize.Parcelize

@Parcelize
data class TosspaymentsPaypalShipping(
    /**
     * 구매자 전체 이름
     */
    val fullName: String? = null,
    val address: TosspaymentsPaypalShippingAddress
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        fullName?.let { put("fullName", fullName) }
        put("address", address.toJson())
    }
}
