// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayBrandpayOptionsUiLabels(
    /**
     * UI에 표시되는 원터치 결제를 대신해 사용할 텍스트. (기본값: "원터치 결제")
     */
    val oneTouchPay: String?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "oneTouchPay" to oneTouchPay?.let { oneTouchPay }
    )
}
