// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsUiPromotionSection
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayWidgetOptionsUi(
    val promotionSection: TossBrandpayWidgetOptionsUiPromotionSection?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        promotionSection?.let { put("promotionSection", promotionSection.toJson()) }
    }
}
