// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayBrandpayOptionsUiNavigationBar(
    /**
     * 내비게이션 바 사용 여부. (기본값: true)
     */
    val visible: Boolean?,
    /**
     * 내비게이션 바 위쪽에 설정할 여백 값. 값의 단위는 px
     */
    val paddingTop: Long?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        visible?.let { put("visible", visible) }
        paddingTop?.let { put("paddingTop", paddingTop) }
    }
}
