// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TosspaymentsPaypalShipping
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

/**
 * 판매자 보호/위험 관리 파라미터
 */
@Parcelize
data class TosspaymentsPaypal(
    val shipping: TosspaymentsPaypalShipping? = null,
    /**
     * 페이팔 STC로 전달되어 부정거래/리스크 평가에 활용됩니다.
     * 키 정의는 [페이팔 STC 문서](https://static.tosspayments.com/public/STC.pdf)를 참고하세요.
     */
    val setTransactionContext: @RawValue Map<String, Any?>? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        shipping?.let { put("shipping", shipping.toJson()) }
        setTransactionContext?.let { put("setTransactionContext", setTransactionContext) }
    }
}
