// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayWidgetOptionsUiPromotionSectionDescription(
    /**
     * 결제 혜택 영역을 보여줄지 여부. 기본값은 true
     */
    val visible: Boolean? = null,
    /**
     * 결제 혜택의 상세 설명을 보여줄지 여부. 각 카드사의 결제 혜택을 자세히 설명 함. 기본값은 false
     */
    val defaultOpen: Boolean? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        visible?.let { put("visible", visible) }
        defaultOpen?.let { put("defaultOpen", defaultOpen) }
    }
}
