// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class TosspaymentsPaypalShippingAddress(
    /**
     * 국가 코드 (ISO-3166 alpha-2, 예: "US")
     */
    val country: String,
    /**
     * 도로명/건물/번지
     */
    val line1: String? = null,
    /**
     * 상세 주소
     */
    val line2: String? = null,
    /**
     * 주/도 (예: "CA")
     */
    val area1: String? = null,
    /**
     * 도시명 (예: "San Jose")
     */
    val area2: String,
    /**
     * 우편번호 (중국, 일본, 프랑스, 독일 등은 필수)
     */
    val postalCode: String? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        put("country", country)
        line1?.let { put("line1", line1) }
        line2?.let { put("line2", line2) }
        area1?.let { put("area1", area1) }
        put("area2", area2)
        postalCode?.let { put("postalCode", postalCode) }
    }
}
