// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayBrandpayOptions
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptions
import kotlinx.parcelize.Parcelize

/**
 * 토스 브랜드페이 bypass 파라미터
 */
@Parcelize
data class TossBrandpayPaymentBypass(
    /**
     * loadBrandpay 호출시 전달하는 세번째 파라미터
     */
    val brandpayOptions: TossBrandpayBrandpayOptions?,
    /**
     * 브랜드페이 위젯 render() 함수 호출시 전달하는 두번째 파라미터
     */
    val widgetOptions: TossBrandpayWidgetOptions?,
    /**
     * 카드사 할인코드
     */
    val discountCode: String?,
    /**
     * 등록되어 있는 결제수단 중 하나를 지정해서 바로 결제하고 싶을 때 사용
     */
    val methodId: String?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        brandpayOptions?.let { put("brandpayOptions", brandpayOptions.toJson()) }
        widgetOptions?.let { put("widgetOptions", widgetOptions.toJson()) }
        discountCode?.let { put("discountCode", discountCode) }
        methodId?.let { put("methodId", methodId) }
    }
}
