// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsMethodType
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayWidgetOptionsUi
import kotlinx.parcelize.Parcelize

/**
 * 브랜드페이 위젯 render() 함수 호출시 전달하는 두번째 파라미터
 */
@Parcelize
data class TossBrandpayWidgetOptions(
    /**
     * 위젯에 보여줄 결제 수단. 예) 카드 전달시 등록한 결제 수단 중 카드만 노출 됨
     */
    val methodType: TossBrandpayWidgetOptionsMethodType?,
    /**
     * 위젯에서 기본 결제 수단으로 선택할 결제 수단의 ID
     */
    val methodId: String?,
    val ui: TossBrandpayWidgetOptionsUi?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        methodType?.let { put("methodType", methodType.toJson()) }
        methodId?.let { put("methodId", methodId) }
        ui?.let { put("ui", ui.toJson()) }
    }
}
