// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.type.entity.bypass.payment.TossBrandpayWidgetOptionsUiPromotionSection
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayWidgetOptionsUi(
    val promotionSection: TossBrandpayWidgetOptionsUiPromotionSection?
) : Parcelable {
    fun toJson(): Map<String, Any?> = mapOf(
        "promotionSection" to promotionSection?.let { promotionSection.toJson() }
    )
}
