// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayBrandpayOptionsUiButtonStyle
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayBrandpayOptionsUiLabels
import io.portone.sdk.android.type.entity.bypass.payment.TossBrandpayBrandpayOptionsUiNavigationBar
import kotlinx.parcelize.Parcelize

@Parcelize
data class TossBrandpayBrandpayOptionsUi(
    /**
     * UI의 메인 색상. (기본값: #3182f6)
     */
    val highlightColor: String?,
    /**
     * 버튼 스타일
     * 
     * - default(기본값): 모서리가 둥글고 주변에 여백을 가진 버튼
     * - full: 하단 영역이 전부 채워지는 형태의 버튼
     */
    val buttonStyle: TossBrandpayBrandpayOptionsUiButtonStyle?,
    val labels: TossBrandpayBrandpayOptionsUiLabels?,
    val navigationBar: TossBrandpayBrandpayOptionsUiNavigationBar?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        highlightColor?.let { put("highlightColor", highlightColor) }
        buttonStyle?.let { put("buttonStyle", buttonStyle.toJson()) }
        labels?.let { put("labels", labels.toJson()) }
        navigationBar?.let { put("navigationBar", navigationBar.toJson()) }
    }
}
