// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * Triple-A bypass 파라미터
 */
@Parcelize
data class TripleABypass(
    /**
     * **결제자 신원 증명 정보**
     * 
     * 신분증, 여권 등 결제자의 신원을 증명할 수 있는 자료의 URL을 입력합니다.
     * 
     * SGD 1500 이상의 결제 등 결제자 신원 조회가 필요한 경우에, `payer_poi`를 입력하면 별도의 신원 요청 과정을 거치지 않고 결제가 진행됩니다.
     */
    val payerPoi: String? = null,
    /**
     * **배송비**
     * 
     * 결제창에 표시할 배송비를 정수로 나타냅니다.
     * `products`가 지정된 경우에만 사용할 수 있습니다.
     * 
     * 해외 통화의 경우 통화의 최소 단위(minor unit)를 기준으로 합니다. 예를 들어, USD의 최소 단위는 센트(0.01 USD)이므로, 6 USD의 경우 100배하여 600으로 입력합니다.
     * 
     * 최소 단위는 [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)에 표준화된 것을 기준으로 합니다.
     * 
     * - KRW: 1배
     * - USD: 100배
     * - JPY: 1배
     */
    val shippingCost: Long? = null,
    /**
     * **배송비 할인 금액**
     * 
     * 결제창에 표시할 배송비 할인 금액을 정수로 나타냅니다.
     * `products`가 지정된 경우에만 사용할 수 있습니다.
     */
    val shippingDiscount: Long? = null,
    /**
     * **세금**
     * 
     * 결제창에 표시할 세금을 정수로 나타냅니다.
     * `products`가 지정된 경우에만 사용할 수 있습니다.
     */
    val taxCost: Long? = null
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        payerPoi?.let { put("payer_poi", payerPoi) }
        shippingCost?.let { put("shipping_cost", shippingCost) }
        shippingDiscount?.let { put("shipping_discount", shippingDiscount) }
        taxCost?.let { put("tax_cost", taxCost) }
    }
}
