// This file is automatically generated by the SDK generator.
// Do not edit this file manually.

package io.portone.sdk.android.type.entity.bypass.payment

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 웰컴페이먼츠 bypass 파라미터
 */
@Parcelize
data class WelcomePaymentBypass(
    /**
     * 메인 로고 URL (크기: 89x19)
     */
    val logoUrl: String?,
    /**
     * 서브 로고 URL (크기: 64x13)
     */
    val logo2Nd: String?,
    /**
     * 다양한 결제 옵션을 설정하기 위한 파라미터 배열입니다.
     * 
     * 가능한 값들은 다음과 같습니다:
     * 
     * - **SKIN(#색상코드)**: 결제 창의 배경 색상 설정 (기본값: #c1272c)
     * - 예시: `SKIN(#fc6b2d)`
     * - **below1000**: 1,000원 미만 결제 허용 여부
     * - **onlyeasypaycode(간편결제코드들)**: 카드 결제창에 렌더링될 간편 결제 리스트 지정
     * - 예시: `onlyeasypaycode(kakaopay:lpay:payco)`
     * - 간편결제코드:
     * - 카카오페이: `kakaopay`
     * - 엘페이: `lpay`
     * - 페이코: `payco`
     * - 토스페이: `tosspay`
     * - **SLIMQUOTA(코드-개월:개월^코드-개월:개월)**: 부분 무이자 할부 옵션
     * - 형식: `SLIMQUOTA(카드코드-할부개월:부분무이자개월^...)`
     * - **paypopup**: 안심 클릭을 팝업 형태로 렌더링 할지 여부
     * - **hppdefaultcorp(통신사코드)**: 휴대폰 소액결제 시 기본 선택 통신사 지정
     * - 예시: `hppdefaultcorp(KTF)`
     * - 통신사코드:
     * - `SKT`: SK 텔레콤
     * - `KTF`: KT
     * - `LGT`: LG 유플러스
     * - `MVNO`: 알뜰폰 전체
     * - `CJH`: 알뜰폰 CJ 헬로 모바일
     * - `KCT`: 알뜰폰 티플러스
     * - `SKL`: 알뜰폰 SK 세븐 모바일
     * - **hppnofix(Y|N)**: 휴대폰 소액결제창에 자동 입력되는 `buyer_tel` 값을 수정할 수 있는지 여부
     * - `Y`: 수정 불가능
     * - `N`: 수정 가능 (기본값)
     * - **va\_ckprice**: 가상계좌 발급 시, 주민번호 채번할 때 금액 체크 기능
     */
    val acceptmethod: List<String>?,
    /**
     * 1. **신용카드 우선 선택 옵션**
     * 
     * - 예시: `selcode=14`
     * - 해당 카드 코드에 해당하는 카드가 선택된 채로 표시
     * - 간편결제는 불가능 (타 카드 선택 가능)
     * 
     * 2. **선택적 표시 옵션**
     * 
     * - 예시 1: `onlycard=visa3d`
     * - 예시 2: `selcode=14:onlycard=visa3d`
     * - 선택적 표시 가능 결제 방식:
     * - 안심결제: `visa3d`
     * - ISP: `isp`
     * - 간편결제: `easypay`
     */
    val pCardOption: String?,
    /**
     * 카드 결제창에 렌더링될 간편 결제 리스트를 지정합니다.
     * 
     * 예시: 카카오페이, 엘페이, 페이코만 렌더링 → `KAKAOPAY:LPAY:PAYCO`
     * 
     * - 카카오페이: `KAKAOPAY`
     * - 엘페이: `LPAY`
     * - 페이코: `PAYCO`
     * - 토스페이: `TOSSPAY`
     */
    val pOnlyEasypaycode: String?,
    /**
     * 결제창 동작을 제어하기 위한 파라미터들을 설정하는 배열입니다.
     * 
     * 가능한 값들은 다음과 같습니다:
     * 
     * - **below1000=Y**: 1,000원 미만 결제 허용 여부
     * - **hpp\_default\_corp=통신사코드**: 휴대폰 소액결제 시 기본 선택 통신사 지정
     * - 예시: `hpp_default_corp=KTF`
     * - 통신사코드:
     * - `SKT`: SK 텔레콤
     * - `KTF`: KT
     * - `LGT`: LG 유플러스
     * - `MVNO`: 알뜰폰 전체
     * - `CJH`: 알뜰폰 CJ 헬로 모바일
     * - `KCT`: 알뜰폰 티플러스
     * - `SKL`: 알뜰폰 SK 세븐 모바일
     * - **hpp\_nofix=Y|N**: 휴대폰 소액결제창에서 자동 입력된 `buyer_tel` 수정 가능 여부
     * - `Y`: 수정 불가능
     * - `N`: 수정 가능 (기본값)
     */
    val pReserved: List<String>?
) : Parcelable {
    fun toJson(): Map<String, Any> = buildMap {
        logoUrl?.let { put("logo_url", logoUrl) }
        logo2Nd?.let { put("logo_2nd", logo2Nd) }
        acceptmethod?.let { put("acceptmethod", acceptmethod) }
        pCardOption?.let { put("P_CARD_OPTION", pCardOption) }
        pOnlyEasypaycode?.let { put("P_ONLY_EASYPAYCODE", pOnlyEasypaycode) }
        pReserved?.let { put("P_RESERVED", pReserved) }
    }
}
