package io.portone.sdk.android.type

enum class CardCompany {
    KOREA_DEVELOPMENT_BANK,
    KFCC,
    SHINHYUP,
    EPOST,
    SAVINGS_BANK_KOREA,
    KAKAO_BANK,
    WOORI_CARD,
    BC_CARD,
    GWANGJU_CARD,
    SAMSUNG_CARD,
    SHINHAN_CARD,
    HYUNDAI_CARD,
    LOTTE_CARD,
    SUHYUP_CARD,
    CITI_CARD,
    NH_CARD,
    JEONBUK_CARD,
    JEJU_CARD,
    HANA_CARD,
    KOOKMIN_CARD,
    K_BANK,
    TOSS_BANK,
    MIRAE_ASSET_SECURITIES;
}
