name: Junie
run-name: Junie run ${{ inputs.run_id }}

permissions: {}

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "id of workflow process"
        required: true
      workflow_params:
        description: "stringified params"
        required: true

jobs:
  call-workflow-passing-data:
    permissions:
      contents: write # Required to let Junie commit repository updates.
      pull-requests: write # Required to let Junie update pull requests.
    uses: jetbrains-junie/junie-workflows/.github/workflows/ej-issue.yml@b4f71597a0a5aaa196d1191efe33f6f77517f792
    with:
      workflow_params: ${{ inputs.workflow_params }}
